### ISSUE TITLE
TimeZone is not set correctly in the SWAG container

### ISSUE THREAD

**Issue by YouveGotMeowxy** [linuxserver/docker-swag#134]
I'm having an issue with the logs showing UTC time even though I've specified my local TZ. I'm using Docker Desktop in WSL2.

Here's my current Swag compose (I set it in both the environment var as well as the mount):

```
 swag:
    image: ghcr.io/linuxserver/swag:latest
    environment:
      TZ: ${TZ}
      URL: my.domain
      SUBDOMAINS: wildcard
      FILE__EMAIL: /run/secrets/CloudFlare-Email
      PUID: 1000
      PGID: 1000
      VALIDATION: dns
      ONLY_SUBDOMAINS: 'true'
      DNSPLUGIN: 'cloudflare'
      FILE__MAXMINDDB_LICENSE_KEY: /run/secrets/Maxmind-Key
      DOCKER_MODS: linuxserver/mods:swag-ffmpeg|linuxserver/mods:swag-geoip2influx
      # Config Ref: https://github.com/linuxserver/docker-mods/tree/swag-geoip2influx
      # Currently removed |linuxserver/mods:swag-imagemagick from above mods, due to it breaking Swag.
      INFLUX_HOST: influxdb
      INFLUX_HOST_PORT: 8086
      INFLUX_DATABASE: nginx
      INFLUX_USER: nginx
      FILE__INFLUX_PASS: /run/secrets/Influx-PW
      SEND_NGINX_LOGS: 'true'
      GEOIP2INFLUX_LOG_LEVEL: info
    volumes:
      - /opt/docker/configs/Swag/config:/config:rw
      - /mnt/d/Logs/swag:/config/log:rw
      - /etc/localtime:/etc/localtime:ro
    #cap_add:
    #  - NET_ADMIN # Optional: Required for fail2ban to modify iptables (ignored in swarm mode)
    ports:
      - 443:443
    secrets:
      - Influx-PW
      - CloudFlare-Email
      - Maxmind-Key
    deploy:
      mode: global
      restart_policy:
        condition: any
    networks:
      - om
```

Then in my logs, it still shows UTC time.. (note that my current time was 10:51 am but logs are showing 3:51 pm)

My basic log shows:

> today at 10:51:11 AM  GEOIP2INFLUX 25/Jun/2021 15:51:11 :: INFO :: Starting geoip2influx..
> today at 10:51:12 AM  GEOIP2INFLUX 25/Jun/2021 15:51:12 :: INFO :: Starting log parsing

and my error log shows:

> 2021/06/25 16:08:05 [error] 689#689: *298 connect() failed (111: Connection refused) while connecting to upstream, client: 10.0.0.2, server: bitwarden.*, request: "GET 

From my terminal:

> /opt/docker/configs/Swag/config/nginx$ date
> Fri Jun 25 11:11:50 CDT 2021
> /opt/docker/configs/Swag/config/nginx$ date -u
> Fri Jun 25 16:11:52 UTC 2021
