### ISSUE TITLE
Only Running Letsencrypt

### ISSUE THREAD

**Issue by AverageHumanoid** [linuxserver/docker-swag#143]
I've been using this image to generate and renew letsencrypt certs but I don't need the container to also run fail2ban, nginx and php-fpm. Is there an existing way to prevent fail2ban, nginx and php-fpm from starting up? If not, I would like to suggest adding an environment variable to delete `/etc/services.d/{fail2ban,nginx,php-fpm}` which should prevent those services (or some other way) from starting.

**Comment by Roxedus** [comment]
There is no plan to implement this. What you essentially want is the certbot/certbot image, as thats effectivly what SWAG becomes when disabling the mentioned services.

**Comment by AverageHumanoid** [comment]
@Roxedus I use this image because of how easy it is to generate certs with DuckDNS and keeping it renewed which I don't think certbot/certbot does. I don't see the issue with having the option but anyway I found the solution by including this in my docker-compose.

```
    volumes:
      - type: tmpfs
        target: /etc/services.d
      - type: bind
        source: ./run
        target: /etc/services.d/cron/run
```
