### ISSUE TITLE
Fail2Ban blocks an internal Docker IP

### ISSUE THREAD

**Issue by Maxattax97** [linuxserver/docker-swag#148]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior
Fail2Ban shouldn't block internal IP's, especially ones from Docker.

## Current Behavior
Fail2Ban is picking up and banning a Docker IP, which causes all of my services under reverse proxy to become inaccessible.

## Steps to Reproduce
I'm not certain what triggers the ban yet, still trying to understand this problem. But what I do know is this fixes it:

```
$ docker exec -it letsencrypt fail2ban-client banned
[{'nginx-http-auth': []}, {'nginx-botsearch': ['172.18.0.1']}, {'nginx-badbots': []}]
$ docker exec -it letsencrypt fail2ban-client unban --all
1
$ docker exec -it letsencrypt fail2ban-client banned
[{'nginx-http-auth': []}, {'nginx-botsearch': []}, {'nginx-badbots': []}]
```

I have Jellyfin hosted in my webstack. The bans are seemingly random, but I do notice it happens a lot while I'm streaming Jellyfin :man_shrugging: .

## Environment
**OS:** Fedora 33 (Server Edition) 
**CPU architecture:** x86_64
**How docker service was installed:**
`moby-engine` from Fedora's official repos.

## Command used to create docker container (run/create/compose/screenshot)
```
  letsencrypt:
    image: linuxserver/swag
    container_name: letsencrypt
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Indianapolis
      - URL=maxocull.com
      - SUBDOMAINS=www,resolute,whoami,dash,cloud,git,dns,office,lidarr,sonarr,radarr,media,torrent,jackett,ci,grafana,search,map,pgadmin,prometheus,portainer,registry,librarian,books,doc,analytics,irc,meet,bazarr,rss,kimai
      - VALIDATION=http # DNS? so can use wildcards
      #- DNSPLUGIN=cloudflare #optional
      #- DUCKDNSTOKEN=<token> #optional
      - EMAIL=max.ocull@protonmail.com
      - DHLEVEL=2048
      - ONLY_SUBDOMAINS=false
      - EXTRA_DOMAINS=maxocull.net,www.maxocull.net,resolute.maxocull.net,whoami.maxocull.net,dash.maxocull.net,cloud.maxocull.net,git.maxocull.net,dns.maxocull.net,office.maxocull.net,lidarr.maxocull.net,sonarr.maxocull.net,radarr.maxocull.net,media.maxocull.net,torrent.maxocull.net,jackett.maxocull.net,ci.maxocull.net,grafana.maxocull.net,search.maxocull.net,map.maxocull.net,pgadmin.maxocull.net,prometheus.maxocull.net,portainer.maxocull.net,registry.maxocull.net,librarian.maxocull.net,books.maxocull.net,doc.maxocull.net,analytics.maxocull.net,irc.maxocull.net,meet.maxocull.net,bazarr.maxocull.net,rss.maxocull.net,kimai.maxocull.net
      - STAGING=false # Enable when testing.
    volumes:
      - /opt/flotilla/data/letsencrypt/keys:/config/etc/letsencrypt:Z
      - /opt/flotilla/data/letsencrypt/www:/config/www:Z
      - /opt/flotilla/config/letsencrypt:/config:z
      - /opt/flotilla/data/all/logs/letsencrypt:/config/log:z
    ports:
      - "80:80"
      - "443:443"
    #deploy:
      #resources:
        #limits:
          #memory: "1g"
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    restart: unless-stopped
```

## Docker logs

```
-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/
Brought to you by linuxserver.io
-------------------------------------
To support the app dev(s) visit:
Certbot: https://supporters.eff.org/donate/support-work-on-certbot
To support LSIO projects visit:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------
User uid:    1000
User gid:    1000
-------------------------------------
[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 20-config: executing...
[cont-init.d] 20-config: exited 0.
[cont-init.d] 30-keygen: executing...
using keys found in /config/keys
[cont-init.d] 30-keygen: exited 0.
[cont-init.d] 50-config: executing...
Variables set:
PUID=1000
PGID=1000
TZ=America/Indianapolis
URL=maxocull.com
SUBDOMAINS=www,resolute,whoami,dash,cloud,git,dns,office,lidarr,sonarr,radarr,media,torrent,jackett,ci,grafana,search,map,pgadmin,prometheus,portainer,registry,librarian,books,doc,analytics,irc,meet,bazarr,rss,kimai
EXTRA_DOMAINS=maxocull.net,www.maxocull.net,resolute.maxocull.net,whoami.maxocull.net,dash.maxocull.net,cloud.maxocull.net,git.maxocull.net,dns.maxocull.net,office.maxocull.net,lidarr.maxocull.net,sonarr.maxocull.net,radarr.maxocull.net,media.maxocull.net,torrent.maxocull.net,jackett.maxocull.net,ci.maxocull.net,grafana.maxocull.net,search.maxocull.net,map.maxocull.net,pgadmin.maxocull.net,prometheus.maxocull.net,portainer.maxocull.net,registry.maxocull.net,librarian.maxocull.net,books.maxocull.net,doc.maxocull.net,analytics.maxocull.net,irc.maxocull.net,meet.maxocull.net,bazarr.maxocull.net,rss.maxocull.net,kimai.maxocull.net
ONLY_SUBDOMAINS=false
VALIDATION=http
CERTPROVIDER=
DNSPLUGIN=
EMAIL=max.ocull@protonmail.com
STAGING=false
Using Let's Encrypt as the cert provider
SUBDOMAINS entered, processing
SUBDOMAINS entered, processing
Sub-domains processed are:  -d www.maxocull.com -d resolute.maxocull.com -d whoami.maxocull.com -d dash.maxocull.com -d cloud.maxocull.com -d git.maxocull.com -d dns.maxocull.com -d office.maxocull.com -d lidarr.maxocull.com -d sonarr.maxocull.com -d radarr.maxocull.com -d media.maxocull.com -d torrent.maxocull.com -d jackett.maxocull.com -d ci.maxocull.com -d grafana.maxocull.com -d search.maxocull.com -d map.maxocull.com -d pgadmin.maxocull.com -d prometheus.maxocull.com -d portainer.maxocull.com -d registry.maxocull.com -d librarian.maxocull.com -d books.maxocull.com -d doc.maxocull.com -d analytics.maxocull.com -d irc.maxocull.com -d meet.maxocull.com -d bazarr.maxocull.com -d rss.maxocull.com -d kimai.maxocull.com
EXTRA_DOMAINS entered, processing
Extra domains processed are:  -d maxocull.net -d www.maxocull.net -d resolute.maxocull.net -d whoami.maxocull.net -d dash.maxocull.net -d cloud.maxocull.net -d git.maxocull.net -d dns.maxocull.net -d office.maxocull.net -d lidarr.maxocull.net -d sonarr.maxocull.net -d radarr.maxocull.net -d media.maxocull.net -d torrent.maxocull.net -d jackett.maxocull.net -d ci.maxocull.net -d grafana.maxocull.net -d search.maxocull.net -d map.maxocull.net -d pgadmin.maxocull.net -d prometheus.maxocull.net -d portainer.maxocull.net -d registry.maxocull.net -d librarian.maxocull.net -d books.maxocull.net -d doc.maxocull.net -d analytics.maxocull.net -d irc.maxocull.net -d meet.maxocull.net -d bazarr.maxocull.net -d rss.maxocull.net -d kimai.maxocull.net
E-mail address entered: max.ocull@protonmail.com
http validation is selected
Certificate exists; parameters unchanged; starting nginx
Currently using the user provided GeoLite2-City.mmdb.
If you want to enable weekly auto-updates of the database, retrieve a free license key from MaxMind,
and add a new env variable "MAXMINDDB_LICENSE_KEY", set to your license key.
[cont-init.d] 50-config: exited 0.
[cont-init.d] 60-renew: executing...
The cert does not expire within the next day. Letting the cron script handle the renewal attempts overnight (2:08am).
[cont-init.d] 60-renew: exited 0.
[cont-init.d] 70-templates: executing...
**** The following nginx confs have different version dates than the defaults that are shipped. ****
**** This may be due to user customization or an update to the defaults. ****
**** To update them to the latest defaults shipped within the image, delete these files and restart the container. ****
**** If they are user customized, check the date version at the top and compare to the upstream changelog via the link. ****
/config/nginx/ssl.conf
/config/nginx/site-confs/default
/config/nginx/proxy.conf
/config/nginx/nginx.conf
/config/nginx/authelia-server.conf
/config/nginx/authelia-location.conf
**** The following reverse proxy confs have different version dates than the samples that are shipped. ****
**** This may be due to user customization or an update to the samples. ****
**** You should compare them to the samples in the same folder to make sure you have the latest updates. ****
/config/nginx/proxy-confs/sonarr.subdomain.conf
/config/nginx/proxy-confs/radarr.subdomain.conf
/config/nginx/proxy-confs/qbittorrent.subdomain.conf
/config/nginx/proxy-confs/prometheus.subdomain.conf
/config/nginx/proxy-confs/portainer.subdomain.conf
/config/nginx/proxy-confs/pihole.subdomain.conf
/config/nginx/proxy-confs/nextcloud.subdomain.conf
/config/nginx/proxy-confs/lidarr.subdomain.conf
/config/nginx/proxy-confs/lazylibrarian.subdomain.conf
/config/nginx/proxy-confs/jellyfin.subdomain.conf
/config/nginx/proxy-confs/jackett.subdomain.conf
/config/nginx/proxy-confs/heimdall.subdomain.conf
/config/nginx/proxy-confs/grafana.subdomain.conf
/config/nginx/proxy-confs/collabora.subdomain.conf
/config/nginx/proxy-confs/calibre.subdomain.conf
/config/nginx/proxy-confs/bazarr.subdomain.conf
[cont-init.d] 70-templates: exited 0.
[cont-init.d] 90-custom-folders: executing...
[cont-init.d] 90-custom-folders: exited 0.
[cont-init.d] 99-custom-files: executing...
[custom-init] no custom files found exiting...
[cont-init.d] 99-custom-files: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
Server ready
run-parts: /etc/periodic/weekly/libmaxminddb: exit status 1
No MaxMind license key found; exiting. Please enter your license key into /etc/libmaxminddb.cron.conf
```
