### ISSUE TITLE
Problem to use different port numbers for docker host and container

### ISSUE THREAD

**Issue by Hobbabobba** [linuxserver/docker-swag#154]
When i try to map port 8081 on the docker host to 8080 in my container, the container `libreddit` is working and i can access the GUI on port 8081.

Just the reverse proxy doesn´t work. I can connect to `guacamole.mydomainname.duckdns.org` but i get a "bad gateway" when i try to connect to `libreddit.mydomainname.duckdns.org` 

Any ideas how i can fix this problem? 

this is my docker-compose.yml
```
---
version: "2.1"
services:
  swag:
    image: ghcr.io/linuxserver/swag
    container_name: swag
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1001
      - PGID=1001
      - TZ=Europe/Berlin
      - URL=mydomainname.duckdns.org
      - SUBDOMAINS=wildcard
      - VALIDATION=duckdns
      - DUCKDNSTOKEN=mytoken
    volumes:
      - ./config:/config
    ports:
      - 443:443
    restart: always

  guacamole:
    image: oznu/guacamole:armhf
    container_name: guacamole
    environment:
      - EXTENSIONS=auth-totp
    volumes:
      - /home/ubuntu/docker/guacamole:/config
    ports:
      - 8080:8080
    restart: always

  libreddit:
    image: spikecodes/libreddit:arm
    restart: always
    container_name: libreddit
    ports:
      - 8081:8080
    restart: always
```

here is my `libreddit.subdomain.conf` file:
```
server {
    listen 443 ssl;
    listen [::]:443 ssl;

    server_name libreddit.*;

    include /config/nginx/ssl.conf;

    client_max_body_size 0;

    location / {
 
        include /config/nginx/proxy.conf;
        include /config/nginx/resolver.conf;
        set $upstream_app libreddit;
        set $upstream_port 8081;
        set $upstream_proto http;
        proxy_pass $upstream_proto://$upstream_app:$upstream_port;
      
    }

}
```
