### ISSUE TITLE
arm32v7 images broken from arm32v7-1.18.0-ls78

### ISSUE THREAD

**Issue by amarinderca** [linuxserver/docker-swag#157]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior
Latest arm image to run properly, instead it does not start.

## Current Behavior

Image fails to load. No config changes made, reverting to previous image 1.18.0-ls78 gives no error.

See errors in logs section.

## Steps to Reproduce

1. Update to latest version

## Environment

**OS:** Raspbian 10
**CPU architecture:** arm64 (Raspberry Pi 4 Model B)
**How docker service was installed: Offical docker repo**

## Command used to create docker container (run/create/compose/screenshot)

docker compose used

```
services:
  swag:
    hostname: swag
    image: linuxserver/swag:arm32v7-1.18.0-ls78
    container_name: swag
    mac_address: redacted
    dns:
      - 127.0.0.1
      - 192.168.1.1 # Points to pihole
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
      - URL=chee.ma
      - SUBDOMAINS=wildcard
      - VALIDATION=dns
      - DNSPLUGIN=cloudflare
      - EMAIL=redacted
      - ONLY_SUBDOMAINS=false
      - STAGING=false
    volumes:
      - /home/pi/swag:/config
    networks:
      backend:
      main_network:
        ipv4_address: 192.168.1.92
    labels:
      - com.centurylinklabs.watchtower.enable=true
    restart: unless-stopped
networks:
  backend:
  main_network:
    driver: macvlan
    driver_opts:
      parent: eth0
    ipam:
      config:
        - subnet: 192.168.1.0/24
          gateway: 192.168.1.1
          ip_range: 192.168.1.192/28
```

## Docker logs

```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
s6-envuidgid: fatal: unknown user: root
s6-envuidgid: fatal: unknown user: root
s6-envuidgid: fatal: unknown user: root
s6-envuidgid: fatal: unknown user: root
s6-envuidgid: fatal: unknown user: root

s6-envuidgid: fatal: unknown user: root
s6-envuidgid: fatal: unknown user: root
s6-envuidgid: fatal: unknown user: root
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 01-envfile: executing...
foreground: warning: unable to spawn /var/run/s6/etc/cont-init.d/01-envfile: Permission denied
[cont-init.d] 01-envfile: exited 127.
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.
```
