### ISSUE TITLE
http validation not available out of the box

### ISSUE THREAD

**Issue by spockz** [linuxserver/docker-swag#16]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

If you are new to Docker or this application our issue tracker is **ONLY** used for reporting bugs or requesting features. Please use [our discord server](https://discord.gg/YWrKVTn) for general support.

------------------------------

## Expected Behavior
Running the image like below should result in a container hosting the challenges on `:80/.well-known/acme-challenge`.
```
---
version: "2.1"
services:
  swag:
    image: linuxserver/swag
    container_name: swag
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Amsterdam
      - URL=home.spockz.nl
      - SUBDOMAINS=dockerhost
      - VALIDATION=httpl
      - EMAIL=redacted #optional
      - ONLY_SUBDOMAINS=false #optional
      - EXTRA_DOMAINS= #optional
      - STAGING=true #optional
    volumes:
      - /home/rancher/letsencrypt/config:/config
    ports:
      - 443:443
      - 8444:80 #optional
    restart: unless-stopped
```

## Current Behavior
The port 80 appears not to be bound. From an attached shell:

```
 root@6e80ae52c0d1:/# curl localhost:80/
curl: (7) Failed to connect to localhost port 80: Connection refused
```

## Steps to Reproduce

1. `docker-compose up` with the contents above.

## Environment
**OS:**  RancherOS     
**CPU architecture:** x86_64
**How docker service was installed:**      
part of rancheros

## Command used to create docker container (run/create/compose/screenshot)
see above.

## Docker logs
```
 [cont-init.d] 30-keygen: exited 0.

[cont-init.d] 50-config: executing... 

Variables set:


0


0

TZ=Europe/Amsterdam

URL=home.spockz.nl

SUBDOMAINS=dockerhost

EXTRA_DOMAINS=

ONLY_SUBDOMAINS=false

VALIDATION=http

DNSPLUGIN=

EMAIL=redacted

STAGING=true


NOTICE: Staging is active

SUBDOMAINS entered, processing

SUBDOMAINS entered, processing

Sub-domains processed are:  -d dockerhost.home.spockz.nl

E-mail address entered: redacted

http validation is selected

Different validation parameters entered than what was used before. Revoking and deleting existing certificate, and an updated one will be created

nerating new certificate

Saving debug log to /var/log/letsencrypt/letsencrypt.log

Plugins selected: Authenticator standalone, Installer None

Obtaining a new certificate

Performing the following challenges:

http-01 challenge for dockerhost.home.spockz.nl
Waiting for verification...

Challenge failed for domain dockerhost.home.spockz.nl

http-01 challenge for dockerhost.home.spockz.nl

Cleaning up challenges

Some challenges have failed.

IMPORTANT NOTES:

 - The following errors were reported by the server:


   Domain: dockerhost.home.spockz.nl

   Type:   connection

   Detail: Fetching

   http://dockerhost.home.spockz.nl/.well-known/acme-challenge/_mk792RfhUgnWANx_7Q4pzGKzteN_eK7bZWHrZvQ9tA:

   Timeout during connect (likely firewall problem)
```
