### ISSUE TITLE
Only first subdomain is considered

### ISSUE THREAD

**Issue by bjoernbrings** [linuxserver/docker-swag#198]
## Expected Behavior
Certificates should be generated for all subdomains specified

## Current Behavior
Only the first subdomain gets a certificate

## Steps to Reproduce
See full parameters below. If I specify
SUBDOMAINS=mail,nextcloud,www
only for the 'mail' subdomain a certificate is generated. In the live folder there exists only a directory for the 'mail' subdomain (or whatever is mentioned first in subdomains though in the logs it states that it will request certificates for all domains).

## Environment
**OS:** debian 11
**CPU architecture:** x86_64
**How docker service was installed:** Via debian

## Command used to create docker container (run/create/compose/screenshot)
Container creation was done via portainer.
```
version: "2.1"
services:
  swag_letsencrypt:
    image: linuxserver/swag:latest
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
      - URL=**********.de
      - VALIDATION=http
      - SUBDOMAINS=mail,nextcloud,www #optional
      - CERTPROVIDER= #optional
      - DNSPLUGIN=cloudflare #optional
      - PROPAGATION= #optional
      - DUCKDNSTOKEN= #optional
      - EMAIL= #optional
      - ONLY_SUBDOMAINS=true #optional
      - EXTRA_DOMAINS= #optional
      - STAGING=false #optional
    volumes:
      - /mnt/docker/swag_letsencrypt:/config
    ports:
      - 443:443
      - 80:80 #optional
```

## Docker logs

> -------------------------------------
>           _         ()
>          | |  ___   _    __
>          | | / __| | |  /  \
>          | | \__ \ | | | () |
>          |_| |___/ |_|  \__/
> 
> 
> Brought to you by linuxserver.io
> -------------------------------------
> 
> To support the app dev(s) visit:
> Certbot: https://supporters.eff.org/donate/support-work-on-certbot
> 
> To support LSIO projects visit:
> https://www.linuxserver.io/donate/
> -------------------------------------
> GID/UID
> -------------------------------------
> 
> User uid:    1000
> User gid:    1000
> -------------------------------------
> 
> [cont-init.d] 10-adduser: exited 0.
> [cont-init.d] 20-config: executing... 
> [cont-init.d] 20-config: exited 0.
> [cont-init.d] 30-keygen: executing... 
> using keys found in /config/keys
> [cont-init.d] 30-keygen: exited 0.
> [cont-init.d] 50-config: executing... 
> Variables set:
>       
> 0
>       
> 0
> TZ=Europe/Berlin
> URL=**********.de
> SUBDOMAINS=mail,nextcloud,www
> EXTRA_DOMAINS=
> ONLY_SUBDOMAINS=true
> VALIDATION=http
> CERTPROVIDER=
> DNSPLUGIN=cloudflare
> EMAIL=
> STAGING=false
> 
> Using Let's Encrypt as the cert provider
> SUBDOMAINS entered, processing
> SUBDOMAINS entered, processing
> Only subdomains, no URL in cert
> Sub-domains processed are:  -d mail.**********.de -d nextcloud.**********.de -d www.**********.de
> No e-mail address entered or address invalid
> http validation is selected
> Certificate exists; parameters unchanged; starting nginx
> [cont-init.d] 50-config: exited 0.
> [cont-init.d] 60-renew: executing... 
> The cert does not expire within the next day. Letting the cron script handle the renewal attempts overnight (2:08am).
> [cont-init.d] 60-renew: exited 0.
> [cont-init.d] 70-templates: executing... 
> [cont-init.d] 70-templates: exited 0.
> [cont-init.d] 90-custom-folders: executing... 
> [cont-init.d] 90-custom-folders: exited 0.
> [cont-init.d] 99-custom-files: executing... 
> [custom-init] no custom files found exiting...
> [cont-init.d] 99-custom-files: exited 0.
> [cont-init.d] done.
> [services.d] starting services
> [services.d] done.
>       
> Server ready
> 
>
