### ISSUE TITLE
Access logs are empty

### ISSUE THREAD

**Issue by Sonlis** [linuxserver/docker-swag#212]
## Expected Behavior
When the container is reached through http request, I expect access logs to logged `/var/log/nginx/access.log` as it is configured in `/etc/nginx/nginx.conf` : 
``` 
# Specifies the main log format.
	log_format main '$remote_addr - $remote_user [$time_local] "$request" '
			'$status $body_bytes_sent "$http_referer" '
			'"$http_user_agent" "$http_x_forwarded_for"';

	# Sets the path, format, and configuration for a buffered log write.
	access_log /var/log/nginx/access.log main;
``` 

## Current Behavior
`/var/log/nginx/access.log` does not exist, and creating it does not resolve the problem, the file stays empty even when requests hit the instance.

## Steps to Reproduce
1. Install via docker-compose this instance of swag: 
```
version: "3.9"
services:
  reverse-proxy:
    image: linuxserver/swag
    container_name: reverse_proxy
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Helsinki
      - URL=<url>
      - VALIDATION=http
      - SUBDOMAINS=www, #optional
      - CERTPROVIDER= #optional
     # - DNSPLUGIN=cloudflare #optional
      - PROPAGATION= #optional
      - DUCKDNSTOKEN= #optional
      - EMAIL=<email_address>#optional
      - ONLY_SUBDOMAINS=false #optional
      - EXTRA_DOMAINS= #optional
      - STAGING=false #optional
    volumes:
      - ./data/swag-config:/config/nginx/proxy-confs
    ports:
      - 443:443
      - 80:80 #optional
    restart: unless-stopped 
```
2. run `docker exec reverse_proxy touch /var/log/nginx/access.log`

## Environment
**OS:Raspbian
**CPU architecture: arm64
