### ISSUE TITLE
Issue with route53 DNS auth

### ISSUE THREAD

**Issue by brendandebeasi** [linuxserver/docker-swag#218]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

Docker does not appear to be using available route53 auth. Getting `InvalidClientTokenId` and not seeing the key being used in my AWS console. 

Probably doing something wrong, but can't figure out what it is.

------------------------------

## Expected Behavior
Cert should generate successfully

## Current Behavior
`InvalidClientTokenId`

## Steps to Reproduce
1. `docker-compose up`
2. wait for logs

## Environment
**OS:** raspbian
**CPU architecture:** aarch64
**How docker service was installed:**
 from the official docker repo

## Command used to create docker container (run/create/compose/screenshot)
`docker-compose up`

docker-compose.yml:
```
---
version: "2.1"
services:
  swag:
    image: lscr.io/linuxserver/swag
    container_name: swag
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
      - URL=MY DOMAIN
      - VALIDATION=dns
      - SUBDOMAINS= #optional
      - CERTPROVIDER= #optional
      - DNSPLUGIN=route53 #optional
      - PROPAGATION= #optional
      - DUCKDNSTOKEN= #optional
      - EMAIL=MY EMAIL #optional
      - ONLY_SUBDOMAINS=false #optional
      - EXTRA_DOMAINS= #optional
      - STAGING=false #optional
    volumes:
      - /path/to/appdata/config:/config
    ports:
      - 443:443
      - 80:80 #optional
    restart: unless-stopped
```
## Docker logs
```
root@docker1:~/swag# docker-compose up
Recreating swag ... done
Attaching to swag
swag    | [s6-init] making user provided files available at /var/run/s6/etc...exited 0.
swag    | [s6-init] ensuring user provided files have correct perms...exited 0.
swag    | [fix-attrs.d] applying ownership & permissions fixes...
swag    | [fix-attrs.d] done.
swag    | [cont-init.d] executing container initialization scripts...
swag    | [cont-init.d] 01-envfile: executing...
swag    | [cont-init.d] 01-envfile: exited 0.
swag    | [cont-init.d] 02-tamper-check: executing...
swag    | [cont-init.d] 02-tamper-check: exited 0.
swag    | [cont-init.d] 10-adduser: executing...
swag    |
swag    | -------------------------------------
swag    |           _         ()
swag    |          | |  ___   _    __
swag    |          | | / __| | |  /  \
swag    |          | | \__ \ | | | () |
swag    |          |_| |___/ |_|  \__/
swag    |
swag    |
swag    | Brought to you by linuxserver.io
swag    | -------------------------------------
swag    |
swag    | To support the app dev(s) visit:
swag    | Certbot: https://supporters.eff.org/donate/support-work-on-certbot
swag    |
swag    | To support LSIO projects visit:
swag    | https://www.linuxserver.io/donate/
swag    | -------------------------------------
swag    | GID/UID
swag    | -------------------------------------
swag    |
swag    | User uid:    1000
swag    | User gid:    1000
swag    | -------------------------------------
swag    |
swag    | [cont-init.d] 10-adduser: exited 0.
swag    | [cont-init.d] 20-config: executing...
swag    | [cont-init.d] 20-config: exited 0.
swag    | [cont-init.d] 30-keygen: executing...
swag    | using keys found in /config/keys
swag    | [cont-init.d] 30-keygen: exited 0.
swag    | [cont-init.d] 50-config: executing...
swag    | Variables set:
swag    | PUID=1000
swag    | PGID=1000
swag    | TZ=America/Los_Angeles
swag    | URL=MYDOMAIN HERE
swag    | SUBDOMAINS=
swag    | EXTRA_DOMAINS=
swag    | ONLY_SUBDOMAINS=false
swag    | VALIDATION=dns
swag    | CERTPROVIDER=
swag    | DNSPLUGIN=route53
swag    | EMAIL=EMAIL HERE
swag    | STAGING=false
swag    |
swag    | Using Let's Encrypt as the cert provider
swag    | No subdomains defined
swag    | E-mail address entered: EMAIL HERE
swag    | dns validation via route53 plugin is selected
swag    | Different validation parameters entered than what was used before. Revoking and deleting existing certificate, and an updated one will be created
swag    | Generating new certificate
swag    | Saving debug log to /var/log/letsencrypt/letsencrypt.log
swag    | Account registered.
swag    | Requesting a certificate for MYDOMAIN HERE
swag    | An error occurred (InvalidClientTokenId) when calling the ListHostedZones operation: The security token included in the request is invalid.
swag    | To use certbot-dns-route53, configure credentials as described at https://boto3.readthedocs.io/en/latest/guide/configuration.html#best-practices-for-configuring-credentials and add the necessary permissions for Route53 access.
swag    | Ask for help or search for solutions at https://community.letsencrypt.org. See the logfile /var/log/letsencrypt/letsencrypt.log or re-run Certbot with -v for more details.
swag    | ERROR: Cert does not exist! Please see the validation error above. Make sure you entered correct credentials into the /config/dns-conf/route53.ini file.```

From the log file in the container ```
...
2022-02-26 12:47:53,252:DEBUG:botocore.utils:IMDS ENDPOINT: http://169.254.169.254/
2022-02-26 12:47:53,259:DEBUG:botocore.credentials:Looking for credentials via: env
2022-02-26 12:47:53,259:DEBUG:botocore.credentials:Looking for credentials via: assume-role
2022-02-26 12:47:53,260:DEBUG:botocore.credentials:Looking for credentials via: assume-role-with-web-identity
2022-02-26 12:47:53,260:DEBUG:botocore.credentials:Looking for credentials via: sso
2022-02-26 12:47:53,260:DEBUG:botocore.credentials:Looking for credentials via: shared-credentials-file
2022-02-26 12:47:53,261:DEBUG:botocore.credentials:Looking for credentials via: custom-process
2022-02-26 12:47:53,261:DEBUG:botocore.credentials:Looking for credentials via: config-file
2022-02-26 12:47:53,263:INFO:botocore.credentials:Credentials found in config file: /config/dns-conf/route53.ini
...
```

root@docker1:~/swag# ls -alh config/dns-conf/
```total 12K
drwxr-xr-x 2 root root 4.0K Feb 26 20:46 .
drwxr-xr-x 3 root root 4.0K Feb 26 20:37 ..
-rw-r--r-- 1 root root  112 Feb 26 20:44 route53.ini```

route53.ini
```[default]
aws_access_key_id=ROOT KEYID HERE
aws_secret_access_key=ROOT KEY SECRET```
