### ISSUE TITLE
"Connection refused" After Certificate Renewal

### ISSUE THREAD

**Issue by AndrewPaglusch** [linuxserver/docker-swag#225]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior
When a Let's Encrypt certificate is scheduled for renewal, it should renew and reload Nginx so that the new certificate is used. Incoming connections to Swag should continue to work.

## Current Behavior
When a Let's Encrypt certificate is renewed, Nginx (inside Swag) refuses incoming connections on ports 80 and 443.

I host multiple different instances of [Seafile](https://www.seafile.com/en/home/) behind Swag. Most on dedicated servers. All are configured the same. This issue affects them all. When a certificate is renewed automatically by Swag, the backend application (Seafile, in this case) goes down. A quick `docker restart swag` gets everything up and running right away.

```
[root@redacted-seafile01 ~]# curl -viLk http://localhost
* About to connect() to localhost port 80 (#0)
*   Trying ::1...
* Connected to localhost (::1) port 80 (#0)
> GET / HTTP/1.1
> User-Agent: curl/7.29.0
> Host: localhost
> Accept: */*
>
* Recv failure: Connection reset by peer
* Closing connection 0
curl: (56) Recv failure: Connection reset by peer
```

```
[root@redacted-seafile01 ~]# docker exec -t swag curl -viLk http://localhost:80
*   Trying 127.0.0.1:80...
* connect to 127.0.0.1 port 80 failed: Connection refused
*   Trying ::1:80...
* Immediate connect fail for ::1: Network unreachable
* Failed to connect to localhost port 80 after 0 ms: Connection refused
* Closing connection 0
curl: (7) Failed to connect to localhost port 80 after 0 ms: Connection refused
```

## Steps to Reproduce

1. Install swag (`image: ghcr.io/linuxserver/swag`)
2. Configure DNS challenge with Cloudflare
3. Set up Seafile in same `docker-compose.yml` file
4. Configure Swag to proxy to Seafile:

**Swag Seafile Config**
```
[root@redacted-seafile01 ~]# cat /opt/docker/swag/config/nginx/site-confs/cloud.redacted.com.conf
server {
	listen 80;
	listen [::]:80;
	server_name cloud.redacted.com;
	return 301 https://$host$request_uri;
}

# main server block
server {
	listen 443 ssl http2;
	listen [::]:443 ssl http2;

	server_name cloud.redacted.com;

	# all ssl related config moved to ssl.conf
	include /config/nginx/ssl.conf;

	#allow large uploads
	client_max_body_size 0;

	location / {
	        proxy_pass http://seafile:80;
		proxy_request_buffering off;
		proxy_buffering off;
	        proxy_set_header Host $host;
	        proxy_set_header X-Real-IP $remote_addr;
	        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
	        proxy_set_header X-Forwarded-Proto $scheme;
	}
}
```

5. Restart Swag so that certificate will be generated
6. Wait for renewal (multiple weeks). Nginx/Swag will refuse incoming TCP connections on ports 80 and 443 from inside Swag, inside Seafile, on the host, and from external sources. I have yet to test manually triggering a renewal to see if this can be reproduced more quickly.

## Environment
**OS:** Rocky Linux 8.4
**CPU architecture:** x86_64
**How docker service was installed:**
```
dnf config-manager --add-repo=https://download.docker.com/linux/centos/docker-ce.repo
dnf install docker-ce
```

**OS Information**
```
[root@redacted-seafile01 ~]# cat /etc/os-release
NAME="Rocky Linux"
VERSION="8.4 (Green Obsidian)"
ID="rocky"
ID_LIKE="rhel fedora"
VERSION_ID="8.4"
PLATFORM_ID="platform:el8"
PRETTY_NAME="Rocky Linux 8.4 (Green Obsidian)"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:rocky:rocky:8.4:GA"
HOME_URL="https://rockylinux.org/"
BUG_REPORT_URL="https://bugs.rockylinux.org/"
ROCKY_SUPPORT_PRODUCT="Rocky Linux"
ROCKY_SUPPORT_PRODUCT_VERSION="8"
```

**Kernel**
```
[root@redacted-seafile01 ~]# uname -r
4.18.0-305.10.2.el8_4.x86_64
```

**Docker Version**
```
[root@redacted-seafile01  ~]# docker -v
Docker version 20.10.7, build f0df350
```

**Docker Images Used**
```
[root@redacted-seafile01 ~]# docker images
REPOSITORY                 TAG       IMAGE ID       CREATED         SIZE
ghcr.io/linuxserver/swag   latest    3c1fab54ecd2   2 months ago    395MB
seafileltd/seafile-mc      latest    5653eeeb2d86   7 months ago    931MB
mariadb                    10.1      895244a22f37   11 months ago   352MB
memcached                  1.5.6     855fdf342eda   4 years ago     58.6MB
```

**Letsencrypt Logs**
```
<------------------------------------------------->
cronjob running on Mon Apr 4 02:08:00 CDT 2022
Running certbot renew
Saving debug log to /var/log/letsencrypt/letsencrypt.log

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Processing /etc/letsencrypt/renewal/redacted.com.conf
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Renewing an existing certificate for redacted.com and cloud.redacted.com
Unsafe permissions on credentials configuration file: /config/dns-conf/cloudflare.ini
Waiting 10 seconds for DNS changes to propagate

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Congratulations, all renewals succeeded:
  /etc/letsencrypt/live/redacted.com/fullchain.pem (success)
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
```

## Command used to create docker container (run/create/compose/screenshot)
```
version: '3'
services:
  swag:
    image: ghcr.io/linuxserver/swag
    container_name: swag
    restart: always
    volumes:
      - ./swag/config:/config
    ports:
      - 443:443
      - 80:80
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
      - URL=redacted.com
      - VALIDATION=dns
      - CERTPROVIDER=letsencrypt
      - SUBDOMAINS=cloud
      - ONLY_SUBDOMAINS=yes
      - DNSPLUGIN=cloudflare #swag/config/dns-conf

  seafile-db:
    image: mariadb:10.1
    #command: --skip-grant-tables
    container_name: seafile-db
    environment:
      - MYSQL_ROOT_PASSWORD=REDACTED
      - MYSQL_LOG_CONSOLE=true
    volumes:
      - ./seafile/seafile-db/data:/var/lib/mysql

  seafile-memcached:
    image: memcached:1.5.6
    container_name: seafile-memcached
    entrypoint: memcached -m 256

  seafile-app:
    image: seafileltd/seafile-mc:latest
    container_name: seafile-app
    volumes:
      - ./seafile/seafile-app/data:/shared   # Requested, specifies the path to Seafile data persistent store.
      - ./seafile/seafile-app/hosts:/etc/hosts
    environment:
      - DB_HOST=seafile-db
      - DB_ROOT_PASSWD=REDACTED
      - SEAFILE_ADMIN_EMAIL=REDACTED
      - SEAFILE_ADMIN_PASSWORD=REDACTED
      - SEAFILE_SERVER_HOSTNAME=cloud.redacted.com
    depends_on:
      - seafile-db
      - seafile-memcached
```

## Docker logs
```
[root@redacted-seafile01 ~]# docker logs --tail 100 swag
run-parts: /etc/periodic/weekly/libmaxminddb: exit status 1
No MaxMind license key found; exiting. Please enter your license key into /etc/libmaxminddb.cron.conf
run-parts: /etc/periodic/weekly/libmaxminddb: exit status 1
No MaxMind license key found; exiting. Please enter your license key into /etc/libmaxminddb.cron.conf
run-parts: /etc/periodic/weekly/libmaxminddb: exit status 1
No MaxMind license key found; exiting. Please enter your license key into /etc/libmaxminddb.cron.conf
No MaxMind license key found; exiting. Please enter your license key into /etc/libmaxminddb.cron.conf
run-parts: /etc/periodic/weekly/libmaxminddb: exit status 1
No MaxMind license key found; exiting. Please enter your license key into /etc/libmaxminddb.cron.conf
run-parts: /etc/periodic/weekly/libmaxminddb: exit status 1
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 01-envfile: executing...
[cont-init.d] 01-envfile: exited 0.
[cont-init.d] 10-adduser: executing...
usermod: no changes

-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/


Brought to you by linuxserver.io
-------------------------------------

To support the app dev(s) visit:
Certbot: https://supporters.eff.org/donate/support-work-on-certbot

To support LSIO projects visit:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------

User uid:    1000
User gid:    1000
-------------------------------------

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 20-config: executing...
[cont-init.d] 20-config: exited 0.
[cont-init.d] 30-keygen: executing...
using keys found in /config/keys
[cont-init.d] 30-keygen: exited 0.
[cont-init.d] 50-config: executing...
Variables set:
PUID=1000
PGID=1000
TZ=America/Chicago
URL=redacted.com
SUBDOMAINS=cloud
EXTRA_DOMAINS=
ONLY_SUBDOMAINS=yes
VALIDATION=dns
CERTPROVIDER=letsencrypt
DNSPLUGIN=cloudflare
EMAIL=
STAGING=

Using Let's Encrypt as the cert provider
SUBDOMAINS entered, processing
SUBDOMAINS entered, processing
Sub-domains processed are:  -d cloud.redacted.com
No e-mail address entered or address invalid
dns validation via cloudflare plugin is selected
Certificate exists; parameters unchanged; starting nginx
[cont-init.d] 50-config: exited 0.
[cont-init.d] 60-renew: executing...
The cert does not expire within the next day. Letting the cron script handle the renewal attempts overnight (2:08am).
[cont-init.d] 60-renew: exited 0.
[cont-init.d] 70-templates: executing...
**** The following nginx confs have different version dates than the defaults that are shipped. ****
**** This may be due to user customization or an update to the defaults. ****
**** To update them to the latest defaults shipped within the image, delete these files and restart the container. ****
**** If they are user customized, check the date version at the top and compare to the upstream changelog via the link. ****
/config/nginx/ssl.conf
/config/nginx/proxy.conf
/config/nginx/nginx.conf

[cont-init.d] 70-templates: exited 0.
[cont-init.d] 90-custom-folders: executing...
[cont-init.d] 90-custom-folders: exited 0.
[cont-init.d] 99-custom-files: executing...
[custom-init] no custom files found exiting...
[cont-init.d] 99-custom-files: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
Server ready
```
