### ISSUE TITLE
(dashboard mod) Issue accessing dashboard when authelia is enabled : HTTP 403

### ISSUE THREAD

**Issue by GuiPoM** [linuxserver/docker-swag#227]
Hello,

I am using Swag deployed on my NAS together with Authelia.
I am also activating some mods, including the nice Dashboard mod. With this mod comes a proxy configuration, dashboard.subdomain.conf.

If I keep the configuration untouched, i.e. as deployed by the mod, the dashboard is working and can be accessed.

Even if this configuration restricts access to dashboard to internal IPs, I want to control who has access to this page. So I uncomment the classic two lines for enabling Authelia on server and on location sections as I am doing for many of my proxies.

Then I get a 403 when I try to access the same dashboard url. 

I must add that Authelia is working well on all my proxies, this includes password as well as Openid connect services. So Authelia is working, and Swag is also working, and Authelia combined with Swag are also working on all my proxies. Dashboard is this only proxy for which I have an issue. 

------------------------------

## Expected Behavior
When I access to dashboard.domain.com, Authelia prompts me for a login, if needed, then redirect to that page.

## Current Behavior
I get a 403.

## Steps to Reproduce
Deploy swag and authelia as described in the documentation. 
For swag, activate the dashboard mod. 
Then go to swag/config/nginx/proxy-confs/dashboard.subdomain.conf and activate two lines:
l71/72
    # enable for Authelia
    include /config/nginx/authelia-server.conf;
l83/84
      # enable for Authelia
        include /config/nginx/authelia-location.conf;
        

## Environment
**OS:** Debian 10, OMV 5.6.26-1.
**CPU architecture:** x86_64 (Intel Pentium Gold G6400)
**How docker service was installed:** Installed from OMV UI with OMV-Extras (apt based installation)

## Command used to create docker container (run/create/compose/screenshot)
```
---
version: "2.1"
services:
  swag:
    image: ghcr.io/linuxserver/swag
    container_name: swag
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=998
      - PGID=1000
      - TZ=Europe/Paris
      - EMAIL=XXX
      - URL=XXX
      - SUBDOMAINS=wildcard
      - VALIDATION=dns
      - DNSPLUGIN=XXX
      - DOCKER_MODS=linuxserver/mods:swag-dashboard
    volumes:
      - /srv/dev-disk-by-uuid-XXX/appdata/swag/config:/config
      - /srv/dev-disk-by-uuid-XXX/appdata/nextcloud/data/nextcloud.log:/nextcloud/nextcloud.log:ro
      - /srv/dev-disk-by-uuid-XXX/appdata/jellyfin/log:/jellyfin/log:ro
    ports:
      - 443:443
      #- 8080:80 #optional
    labels:
      - diun.enable=true
    restart: unless-stopped
    networks:
      - portainer
      - nextcloud
      - heimdall
      - duplicati
      - filebrowser
      - jellyfin
      - librespeed
      - vaultwarden
    
  authelia:
    image: authelia/authelia
    container_name: authelia
    environment:
      - TZ=Europe/Paris
    volumes:
      - /srv/dev-disk-by-uuid-XXX/appdata/authelia/config:/config
    labels:
      - diun.enable=true
    restart: unless-stopped
    networks:
      - portainer
      - nextcloud
      - heimdall
      - duplicati
      - filebrowser
      - jellyfin
      - librespeed
      - vaultwarden
      
 networks:
  default:
    name: swag
```

I know how to change nginx log level but I did not manage to identify why the request to dashboard.domain.com is rejected
