### ISSUE TITLE
Ability to update IP address in DNS servers

### ISSUE THREAD

**Issue by foxy82** [linuxserver/docker-swag#255]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Desired Behavior

SWAG is a really great way to make setting up a SSL reveres proxy really easy. The one additional step that people in a homelab environment often need is the ability to update a dynamic IP address. 

It would be really great if updating a dynamic IP address could be added to this container e.g. using ddclient. 

Whilst I appreciate this makes the container a little bigger and means the separation of concerns is reduced I feel that SWAG is useful due to the fact it doesn't separate the concerns of NGINX, SSL and fail2ban and the missing cherry on top would be updating my dynamic IP address for me.

Would you consider this? Accept a PR for this type of functionality?

## Current Behavior

Currently SWAG can't update a dynamic IP address.

## Alternatives Considered

Alternative is to run a second container to ensure my IP address is kept up to date. Which is a little frustrating especially when I have to add the exact same (cloudflare) settings to SWAG and ddclient.

```
  ddclient:
    image: lscr.io/linuxserver/ddclient:latest
    container_name: ddclient
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - ./ddnsclient_config:/config
    restart: unless-stopped
```
