### ISSUE TITLE
nextcloud.subdomain.conf.sample has example domain whose IP hosts malicious content and typesquats

### ISSUE THREAD

**Issue by TARDISvalet** [linuxserver/docker-swag#259]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior

[I've never filled out an issue form before, so please forgive me if I made formatting errors]
When following instructions to set up proxy to Nextcloud, failure to update a single line should not direct the user to a malicious site. 
Obviously the misconfiguration was my fault and I do appreciate the templates provided! 
However, there may be many examples of bad actors registering domains at default locations hoping to catch people making mistakes like I made. Perhaps example domains should all lead back to SWAG if it is not changed by the user- for security. It would be feasible to inform the admin that a default site is being used in the config and provide that information with the URL used to reach the default site. At the very least, example domains should not lead to external resources if misconfigured.
## Current Behavior

The steps outlined in the provided nextcloud.subdomain.conf.sample can lead to a malicious domain if not changed. The provided example in that file is:
```
# assuming this container is called "swag", edit your nextcloud container's config
# located at /config/www/nextcloud/config/config.php and add the following lines before the ");":
#  'trusted_proxies' => ['swag'],
#  'overwrite.cli.url' => 'https://nextcloud.your-domain.com/',
#  'overwritehost' => 'nextcloud.your-domain.com',
#  'overwriteprotocol' => 'https',
#
# Also don't forget to add your domain name to the trusted domains array. It should look somewhat like this:
#  array (
#    0 => '192.168.0.1:444', # This line may look different on your setup, don't modify it.
#    1 => 'nextcloud.your-domain.com',
#  ),
```
Specifically, if the user doesn't change the default "overwritehost", "overwrite.cli.url", and "trusted domain" values, this happens.
The default values include the URL: "nextcloud.your-domain.com", which is hosted by an IP that also hosts offcie.com and portal.0ffice.com (office.com typos), yuotube.com (youtube.com typo), goodle.com (google.com typo), etc. 
f the user does not realize they have been redirected, they could be phished. Luckily, I noticed I was redirected to a different webpage.
## Steps to Reproduce

1. Set up SWAG as per the instructions
2. Set up the nextcloud.subdomain.conf proxy as outlined in those instructions
3. Copy the lines provided in that sample to Nextcloud's config.php without changing "nextcloud.your-domain.com" to a different domain
4. Access Nextcloud through SWAG and browser will be redirected to different website

## Environment
**OS:** Ubuntu 22.04
**CPU architecture:** x86_64
**How docker service was installed:**

Following the official guide for installing Docker Engine on Ubuntu
## Command used to create docker container (run/create/compose/screenshot)

Used a docker-compose.yml through Portainer (Authelia and Heimdall are also in the SWAG stack)
```
version: "2.1"
services:
  heimdall:
    image: lscr.io/linuxserver/heimdall
    container_name: heimdall
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    volumes:
      - /opt/docker/heimdall:/config
    restart: unless-stopped
  swag:
    image: lscr.io/linuxserver/swag
    container_name: swag
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
      - URL=tardisvalet.xyz
      - SUBDOMAINS=wildcard
      - VALIDATION=dns
      - DNSPLUGIN=cloudflare
      - DOCKER_MODS=linuxserver/mods:swag-dashboard|linuxserver/mods:swag-auto-reload
    volumes:
      - /opt/docker/swag:/config
    ports:
      - 443:443
      - 80:80
      - 81:81
    restart: unless-stopped
  authelia:
    image: ghcr.io/authelia/authelia:4.36.4
    container_name: authelia
    user: "1000:1000"
    environment:
      - TZ=America/New_York
    volumes:
      - /opt/docker/authelia:/config
    restart: unless-stopped
networks:
  default:
    name: tv-network
```
## Docker logs

Not applicable since this issue comes after SWAG has redirected the user. Again, this issue is simply just one about default domains in sample configs.
