### ISSUE TITLE
Docker Swag v1.29.0 cannot be started with linuxserver/mods:swag-maxmind enabled

### ISSUE THREAD

**Issue by Erriez** [linuxserver/docker-swag#260]
## Current Behavior

The Swag server v1.29.0 with  `linuxserver/mods:swag-maxmind` stopped working after Swag restart last night.

```
$ docker-compose up swag
Creating swag ... done
Attaching to swag
swag             | [mod-init] Curl/JQ was not found on this system for Docker mods installing
swag             | fetch http://dl-cdn.alpinelinux.org/alpine/v3.14/main/aarch64/APKINDEX.tar.gz
swag             | fetch http://dl-cdn.alpinelinux.org/alpine/v3.14/community/aarch64/APKINDEX.tar.gz
swag             | (1/1) Installing jq (1.6-r1)
swag             | Executing busybox-1.33.1-r8.trigger
swag             | OK: 255 MiB in 228 packages
swag             | [mod-init] Attempting to run Docker Modification Logic
swag             | [mod-init] Applying linuxserver/mods:swag-maxmind files to container
swag             | s6-rc-compile: fatal: unable to read /etc/s6-overlay/s6-rc.d/init-mods-end/type: No such file or directory
```

## Steps to Reproduce

```yaml
  swag:
    image: ghcr.io/linuxserver/swag:version-1.29.0
    container_name: swag
    restart: always
    ports:
      - 80:80
      - 443:443
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=$DOCKER_UID
      - PGID=$DOCKER_GID
      - EMAIL=${SWAG_EMAIL}
      - URL=${ROOT_DOMAIN}
      - SUBDOMAINS=${SWAG_SUBDOMAINS}
      - VALIDATION=${SWAG_VALIDATION}
      - DNSPLUGIN=${SWAG_DNSPLUGIN}
      - PROPAGATION=${SWAG_PROPAGATION}
      - ONLY_SUBDOMAINS=${SWAG_ONLY_SUBDOMAINS}
      - DOCKER_MODS=linuxserver/mods:swag-maxmind
      - MAXMINDDB_LICENSE_KEY=${MAXMINDDB_LICENSE_KEY}
      - TZ=${TZ}
    volumes:
      - ${VOLUME_DIR}/swag/config:/config
```

Wen removing `DOCKER_MODS` and recreating the container, the Swag server starts correctly.

## Environment
**OS:** Ubuntu 20.04
**CPU architecture:** arm64
**How docker service was installed:**

```bash
$ docker --version
Docker version 20.10.7, build 20.10.7-0ubuntu5~20.04.2

$ docker-compose --version
docker-compose version 1.25.0, build unknown
```

Any suggestions?
