### ISSUE TITLE
dba functions missing in php

### ISSUE THREAD

**Issue by PriamX** [linuxserver/docker-swag#268]
I'm not sure if this is a bug, or an incomplete feature.

When creating a PHP page and attempting to use `dba_open('/config/mydatabase','c','gdbm')` I receive an error that the function is not defined. 

Running a call to `dba_handlers()` this function is also not defined.

Running a call to `phpinfo()` I see that it was configured with the options `--enable-dba=shared` and `--with-gdbm`.

Additionally I see that `gdbmtools` is installed in the container.

I assume then, the intent was that PHP in Swag should be able to use GDBM databases. 

## Expected Behavior
I expect to be able to connect to GDBM databases through Swag's PHP implementation.

## Current Behavior
I am unable to do so because of the undefined functions.

## Steps to Reproduce
1.  Under `/config/www` create a php script, like info.php
2. Add a dba function like `<?php dba_handlers(); ?>`
3. Access the page via a web browser
4. Find the undefined function error in the `/config/log/nginx/error.log` file.

## Environment
Linuxserver.io version:- 1.30.0-ls145 Build-date:- 2022-09-07T15:56:29-05:00
**OS:** Fedora 35
**CPU architecture:** x86_64
**How docker service was installed:** From the official docker repo

## Command used to create docker container (run/create/compose/screenshot)
```
services:
 swag:
    image: linuxserver/swag
    container_name: swag
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=981
      - PGID=100
      - TZ=America/Denver
      - DNS=8.8.8.8,8.8.4.4
      - URL=mydomain.com
      - SUBDOMAINS=
      - VALIDATION=http
      # - DNSPLUGIN=cloudflare #optional
      # - PROPAGATION= #optional
      # - DUCKDNSTOKEN= #optional
      - EMAIL=myemail@gmail.com #optional
      - ONLY_SUBDOMAINS=false #optional
      # - EXTRA_DOMAINS= #optional
      - STAGING=false #optional
    volumes:
      - /docker/appdata/swag:/config
      - /etc/localtime:/etc/localtime:ro
    dns:
      - 8.8.8.8
      - 8.8.4.4
    ports:
      - 443:443
      - 80:80 #optional
    networks:
      - mynet
    healthcheck:
      test: /config/myhealthcheck.sh || exit 1
      interval: 1m30s
      timeout: 10s
      retries: 3
    restart: always
```
## Docker logs
```
[root@myserv ~]# docker exec -it swag tail -20 /config/log/nginx/error.log
2022/09/27 00:29:54 [error] 316#316: *17278 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Error: Call to undefined function dba_handlers() in /config/www/web/info.php:10
Stack trace:
#0 {main}
  thrown in /config/www/web/info.php on line 10" while reading upstream, client: 192.168.0.1, server: _, request: "GET /web/info.php HTTP/2.0", upstream: "fastcgi://127.0.0.1:9000", host: "myserv.mydomain.com"
2022/09/27 00:30:01 [error] 316#316: *17278 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Error: Call to undefined function dba_handlers() in /config/www/web/info.php:10
Stack trace:
#0 {main}
  thrown in /config/www/web/info.php on line 10" while reading upstream, client: 192.168.0.1, server: _, request: "GET /web/info.php HTTP/2.0", upstream: "fastcgi://127.0.0.1:9000", host: "myserv.mydomain.com"
2022/09/27 00:30:04 [error] 316#316: *17278 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Error: Call to undefined function dba_handlers() in /config/www/web/info.php:10
Stack trace:
#0 {main}
  thrown in /config/www/web/info.php on line 10" while reading upstream, client: 192.168.0.1, server: _, request: "GET /web/info.php HTTP/2.0", upstream: "fastcgi://127.0.0.1:9000", host: "myserv.mydomain.com"
2022/09/27 00:31:12 [error] 316#316: *17278 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Error: Call to undefined function dba_open() in /config/www/web/index.php:11
Stack trace:
#0 {main}
  thrown in /config/www/web/index.php on line 11" while reading response header from upstream, client: 192.168.0.1, server: _, request: "GET /web/ HTTP/2.0", upstream: "fastcgi://127.0.0.1:9000", host: "myserv.mydomain.com"
2022/09/27 00:34:26 [error] 316#316: *17278 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Error: Call to undefined function dba_handlers() in /config/www/web/info.php:10
Stack trace:
#0 {main}
  thrown in /config/www/web/info.php on line 10" while reading upstream, client: 192.168.0.1, server: _, request: "GET /web/info.php HTTP/2.0", upstream: "fastcgi://127.0.0.1:9000", host: "myserv.mydomain.com"
[root@myserv ~]#
```
