### ISSUE TITLE
Error when deployed as Microsoft Azure container Instance

### ISSUE THREAD

**Issue by Evil2000** [linuxserver/docker-swag#270]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior

The container should startup an run without any errors.

## Current Behavior
The container fails with `s6-overlay-suexec: fatal: can only run as pid 1` and terminates.

## Steps to Reproduce

Deployment YAML:
```
name: swag  # Name of the container group
apiVersion: '2021-10-01'
location: germanywestcentral
properties: # Properties of container group
  containers: # Array of container instances in the group
  - name: swag # Name of an instance
    properties: # Properties of an instance
      image: linuxserver/swag:latest # Container image used to create the instance
      ports: # External-facing ports exposed on the instance, must also be set in group ipAddress property 
      - protocol: TCP
        port: 80
      - protocol: TCP
        port: 443
      environmentVariables:
      - name: PUID
        value: 1000
      - name: PGID
        value: 1000
      - name: TZ
        value: Europe/Berlin
      - name: URL
        value: swag-test-container.germanywestcentral.azurecontainer.io
      - name: VALIDATION
        value: http
      resources: # Resource requirements of the instance
        requests:
          memoryInGB: 1
          cpu: 1
      volumeMounts: # Array of volume mounts for the instance
      - name: swagconfig
        mountPath: /config
  restartPolicy: Never
  ipAddress: # IP address configuration of container group
    ports:
    - protocol: TCP
      port: 80
    - protocol: TCP
      port: 443
    type: Public
    dnsNameLabel: swag-test-container
  osType: Linux
  volumes: # Array of volumes available to the instances
  - name: swagconfig
    azureFile:
      shareName: swagconfig
      storageAccountName: swagconfigstorage
      storageAccountKey: ... removed ...
  sku: Standard
```
Use `az container create -g swag.rg -n swag -f deployment.yaml` to deploy.
While trying to deploy the swag container as Azure Container instance it fails after starting up with error `s6-overlay-suexec: fatal: can only run as pid 1`

## Environment
**OS:** Linux
**CPU architecture:** x86_64
**How docker service was installed:**
As this is deployed to a service platform, there are no steps to install docker.

## Command used to create docker container (run/create/compose/screenshot)
See above.

## Docker logs
`s6-overlay-suexec: fatal: can only run as pid 1`
