### ISSUE TITLE
[BUG] rootless not possible

### ISSUE THREAD

**Issue by MartinX3** [linuxserver/docker-swag#338]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior
```
s6-overlay-suexec: warning: unable to gain root privileges (is the suid bit set?)
s6-linux-init: fatal: unable to copy /run/s6/basedir/run-image to /run: Operation not permitted
```

### Expected Behavior

Running rootless

A manual with a working configuration and explaination why which permissions are needed.

### Steps To Reproduce
```
securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    add:
      - NET_ADMIN
    drop:
      - ALL
  privileged: false
  readOnlyRootFilesystem: true
  runAsGroup: 1000
  runAsNonRoot: true
  runAsUser: 1000
  seccompProfile:
    type: RuntimeDefault
```

### Environment

```markdown
- OS: Arch Linux
- Podman 4.4.1
```

### CPU architecture

x86-64

### Docker creation

```bash
podman kube play dyndns-https-ip-pod.yaml
```

### Container logs

```bash
s6-overlay-suexec: warning: unable to gain root privileges (is the suid bit set?)
s6-linux-init: fatal: unable to copy /run/s6/basedir/run-image to /run: Operation not permitted
```

### Info
A working security limitation
```
      securityContext:
        allowPrivilegeEscalation: false
        capabilities:
          add:
            - CAP_CHOWN
            - CAP_DAC_OVERRIDE
            - CAP_SETGID
            - NET_ADMIN
          drop:
            - ALL
        privileged: false
        runAsGroup: 1000
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
```

So the container needs to get updated to fully work rootless to reduce the security context capabilities further.
