### ISSUE TITLE
get error of invalid certificate even with the certificate generated correctly and not starts nginx

### ISSUE THREAD

**Issue by mzramna** [linuxserver/docker-swag#34]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

the swag creates a valid certificate,but it acuses that the certificate was not generated and not starts the http server, also this keeps generating new certificates every time the container is restarted so it exceed the letsencrypt certificate generation limit very fast

## Expected Behavior
get the certificate and starts the nginx

## Current Behavior
returns an error even with the message saying it works to generate the certificate,and not starts the nginx,making the http server not works

## Steps to Reproduce
1.install letsencrypt
2.start,wait to create default file
3.stop all containers
4.edit the file to use heimdall
5.restart all containers
6.get error
## Environment
**OS:**
**CPU architecture:**arm32
**How docker service was installed:**
using a docker-compose file associating many of linuxserver containers,like emby,nextcloud and heimdall
## Docker logs
aving debug log to /var/log/letsencrypt/letsencrypt.log
Plugins selected: Authenticator manual, Installer None
Renewing an existing certificate
IMPORTANT NOTES:
 - Congratulations! Your certificate and chain have been saved at:
   /etc/letsencrypt/live/mzramnaserver.duckdns.org/fullchain.pem
   Your key file has been saved at:
   /etc/letsencrypt/live/mzramnaserver.duckdns.org/privkey.pem
   Your cert will expire on 2021-02-10. To obtain a new or tweaked
   version of this certificate in the future, simply run certbot
   again. To non-interactively renew *all* of your certificates, run
   "certbot renew"
 - If you like Certbot, please consider supporting our work by:
   Donating to ISRG / Let's Encrypt:   https://letsencrypt.org/donate
   Donating to EFF:                    https://eff.org/donate-le
ERROR: Cert does not exist! Please see the validation error above. Make sure your DUCKDNSTOKEN is correct.

**Comment by aptalca** [comment]
Post your compose yaml as requested

**Comment by mzramna** [comment]
this is the relevant part of the docker-compose,some parameters are get from an .env file,i supose this is not necessary
```
version: "2.1"

services:
  portainer:
    image: portainer/portainer-ce
    container_name: portainer
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    ports:
      - "9000:9000"
    restart: always

  letsencrypt:
    container_name: letsencrypt
    image: linuxserver/swag:latest
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=$TZ
      - URL=$mzramnaserverURL
      - VALIDATION=duckdns
      - DUCKDNSTOKEN=$duckdnsToken #optional
      - EMAIL=$EMAIL #optional
      - DHLEVEL=2048 #optional
      - ONLY_SUBDOMAINS=true #optional
      - STAGING=false #optional
    volumes:
      - $config_folder/letsencrypt:/config
    ports:
      - "443:443"
      - "80:80" #optional
    restart: unless-stopped

  emby:
    container_name: emby
    image: linuxserver/emby:latest
    volumes:
      - $config_folder/emby:/config
      - $data_folder/media/:/mnt/media
      - $data_folder/torrent_complete:/organize
      - $cert_folder:/certs/
    environment:
      - TZ=$TZ
      - PGID=1000
      - PUID=1000
    restart: unless-stopped

  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
    environment:
      - TZ=$TZ
      - WEBPASSWORD=$PASSWORD
    volumes:
      - $pihole_folder/etc-pihole/:/etc/pihole/
      - $pihole_folder/etc-dnsmasq.d/:/etc/dnsmasq.d/
      - $cert_folder:/certs/
    dns:
      - 127.0.0.1
      - 1.1.1.1
      - 8.8.8.8
    # Recommended but not required (DHCP needs NET_ADMIN)
    #   https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
    cap_add:
      - NET_ADMIN
    restart: always
    
  heimdall:
    image: linuxserver/heimdall:latest
    container_name: heimdall
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=$TZ
    volumes:
      - $config_folder/heimdall:/config/
      - $cert_folder:/certs/
    restart: unless-stopped
    
  nextcloud:
    image: linuxserver/nextcloud:19.0.3-ls100
    container_name: nextcloud
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=$TZ
    volumes:
      - $data_folder/nextcloud:/data
      - $config_folder/nextcloud:/config
    restart: unless-stopped
  
volumes:
  portainer_data:
```
