### ISSUE TITLE
providing volume for /config seems to get overriden by container

### ISSUE THREAD

**Issue by venil7** [linuxserver/docker-swag#37]
------------------------------

## Expected Behavior

config volume is mounted to container

## Current Behavior

config volume is *not*  mounted to container

## Steps to Reproduce
```
version: "3"
services:
  swag:
    image: ghcr.io/linuxserver/swag
    container_name: swag
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - URL=<my domain here>
      - VALIDATION=http
    volumes:
      - ./config:/config <-- this seem to have no effect, local folder `config` exists
    ports:
      - 443:443
      - 80:80
    restart: unless-stopped
```

## Environment
**OS:**
**CPU architecture:** x86_64
**How docker service was installed:**

## Docker logs
no errors in docker log
