### ISSUE TITLE
[BUG] 2.6.0-ls232 not starting

### ISSUE THREAD

**Issue by golles** [linuxserver/docker-swag#404]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

`2.6.0-ls232` isn't starting, `2.6.0-ls231` is fine.

### Steps To Reproduce

I've updated from `2.6.0-ls231` to `2.6.0-ls232` (latest) and noticed the container isn't starting

### Environment

```markdown
- OS: Ubuntu 22.04.3 LTS
- How docker service was installed:
  - Followed this guide: https://docs.docker.com/engine/install/ubuntu/
  - And `sudo apt install docker-compose`
```

### CPU architecture

x86-64

### Docker creation

docker-compose.yaml

```yaml
...
  swag:
    container_name: swag
    restart: unless-stopped
    image: linuxserver/swag:2.6.0-ls232
    cap_add:
      - NET_ADMIN
    volumes:
      - ${DATA_DIR}/swag:/config
    ports:
      - 80:80
      - 443:443
    environment:
      - EMAIL=${PROXY_CERT_EMAIL}
      - URL=${PROXY_CERT_URL}
      - SUBDOMAINS=${PROXY_CERT_SUBDOMAINS}
      - ONLY_SUBDOMAINS=${PROXY_CERT_ONLY_SUBDOMAINS}
      - VALIDATION=${PROXY_CERT_VALIDATION}
      - DNSPLUGIN=${PROXY_CERT_DNSPLUGIN}
      - PROPAGATION=${PROXY_CERT_PROPAGATION}
      - STAGING=${PROXY_CERT_STAGING}
      - DOCKER_MODS=linuxserver/mods:swag-maxmind
      - MAXMINDDB_LICENSE_KEY=${PROXY_MAXMIND_LICENSE_KEY}
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
...
```

.env
```
PGID=1000
PUID=1000
TZ=Europe/Amsterdam
PROXY_CERT_URL=***
PROXY_CERT_EMAIL=***
PROXY_CERT_SUBDOMAINS=wildcard
PROXY_CERT_ONLY_SUBDOMAINS=false
PROXY_CERT_EXTRA_DOMAINS=*.local.***
PROXY_CERT_VALIDATION=dns
PROXY_CERT_DNSPLUGIN=directadmin
PROXY_CERT_PROPAGATION=120
PROXY_CERT_STAGING=false
PROXY_MAXMIND_LICENSE_KEY=***
```

### Container logs

```bash
❯ dcl swag
Attaching to swag
swag                  | [mod-init] Attempting to run Docker Modification Logic
swag                  | [mod-init] Adding linuxserver/mods:swag-maxmind to container
swag                  | [mod-init] Downloading linuxserver/mods:swag-maxmind from lscr.io
swag                  | [mod-init] Installing linuxserver/mods:swag-maxmind
swag                  | [mod-init] linuxserver/mods:swag-maxmind applied to container
swag                  | [migrations] started
swag                  | [migrations] 01-nginx-site-confs-default: skipped
swag                  | [migrations] done
swag                  | ───────────────────────────────────────
swag                  | 
swag                  |       ██╗     ███████╗██╗ ██████╗ 
swag                  |       ██║     ██╔════╝██║██╔═══██╗
swag                  |       ██║     ███████╗██║██║   ██║
swag                  |       ██║     ╚════██║██║██║   ██║
swag                  |       ███████╗███████║██║╚██████╔╝
swag                  |       ╚══════╝╚══════╝╚═╝ ╚═════╝ 
swag                  | 
swag                  |    Brought to you by linuxserver.io
swag                  | ───────────────────────────────────────
swag                  | 
swag                  | To support the app dev(s) visit:
swag                  | Certbot: https://supporters.eff.org/donate/support-work-on-certbot
swag                  | 
swag                  | To support LSIO projects visit:
swag                  | https://www.linuxserver.io/donate/
swag                  | 
swag                  | ───────────────────────────────────────
swag                  | GID/UID
swag                  | ───────────────────────────────────────
swag                  | 
swag                  | User UID:    1000
swag                  | User GID:    1000
swag                  | ───────────────────────────────────────
swag                  | 
swag                  | using keys found in /config/keys
swag                  | Variables set:
swag                  | PUID=1000
swag                  | PGID=1000
swag                  | TZ=Europe/Amsterdam
swag                  | URL=***
swag                  | SUBDOMAINS=wildcard
swag                  | EXTRA_DOMAINS=
swag                  | ONLY_SUBDOMAINS=false
swag                  | VALIDATION=dns
swag                  | CERTPROVIDER=
swag                  | DNSPLUGIN=directadmin
swag                  | EMAIL=***
swag                  | STAGING=false
swag                  | 
swag                  | Please set the DNSPLUGIN variable to one of the following:
swag                  |
```
