### ISSUE TITLE
[BUG] Certbot can not create multiple sub-domains

### ISSUE THREAD

**Issue by ariadi** [linuxserver/docker-swag#484]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Here my docker-compose.yaml

```yaml

services:
###### External Nginx for Gitlab Instance ######
  swag:
    image: lscr.io/linuxserver/swag:latest
    container_name: swag
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    ports:
      - 443:443
      - 80:80
    volumes:
      - ./swag/config:/config
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Jakarta
      - URL=example.com
      - SUBDOMAINS=gitlab,registry
      - ONLY_SUBDOMAINS=true
      - VALIDATION=http
      - EMAIL=me@example.com
      - STAGING=false


```

I run <code>**docker compose up -d swag**</code> and

**<code>docker logs -f swag </code>** to get logs as below

![Screenshot 2024-05-31](https://github.com/linuxserver/docker-swag/assets/14945110/ee1b9d44-74c0-4258-a67d-03e0fcd7713b)

The log says that Certbot will create two subdomains namely: **gitlab.example.com** and **registry.example.com**

but actually it created only one sub-domain, the first one (**gitlab.example.com**)
with no subdomain **registry.example.com**

Then, to prove it, I check into container:

**<code>docker exec -it swag /bin/bash</code>**

![Screenshot 2024-05-31 - 2](https://github.com/linuxserver/docker-swag/assets/14945110/9b124c1d-11c4-4309-8731-89336afe7618)

### Expected Behavior

It should create two certificates.

```bash
gitlab.example.com
```

and

```bash
registry.example.com
```

### Steps To Reproduce

Already mentioned above

### Environment

```markdown
- OS:Ubuntu 20.04 (LTS)
- How docker service was installed: yes, from its distro PM
```

### CPU architecture

x86-64

### Docker creation

```bash
already mentioned above
```

### Container logs

```bash
already given screenshot above.

Thankyou.
```
