### ISSUE TITLE
[BUG] Cannot get secret from environment variable

### ISSUE THREAD

**Issue by Schwitzd** [linuxserver/docker-swag#512]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I'm struggling to configure SWAG to use Cloudflare secret with Docker Swarm secrets

### Expected Behavior

The Cloudflare secrets is read from env variable 

### Steps To Reproduce

This is the docker stack file:

```
version: "3.8"

secrets:
  cloudflare_api_token:
    external: true

services:
  swag:
    image: lscr.io/linuxserver/swag:latest
    cap_add:
      - NET_ADMIN
    hostname: swag-container
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - URL=REDACTED
      - VALIDATION=dns
      - SUBDOMAINS=jellyfin1
      - CERTPROVIDER=
      - DNSPLUGIN=cloudflare
      - EMAIL=REDACTED
      - ONLY_SUBDOMAINS=true
      - STAGING=true
      - FILE__DNS_CLOUDFLARE_API_TOKEN=/run/secrets/cloudflare_api_token
    secrets:
      - cloudflare_api_token
    volumes:
      - /mnt/my_pool/docker/swag/config:/config
    ports:
      - target: 443
        published: 443
        protocol: tcp
        mode: host
    deploy:
      mode: global
      labels:
        - com.centurylinklabs.watchtower.enable=true
```

and `config/dns-conf/cloudflare.ini`

```
# Instructions: https://github.com/certbot/certbot/blob/master/certbot-dns-cloudflare/certbot_dns_cloudflare/__init__.py#L20
# Replace with your values

# With global api key:
#dns_cloudflare_email = cloudflare@example.com
#dns_cloudflare_api_key = 0123456789abcdef0123456789abcdef01234567

# With token (comment out both lines above and uncomment below):
dns_cloudflare_api_token = ${DNS_CLOUDFLARE_API_TOKEN}
```

### Environment

```markdown
- OS: Raspbian
- How docker service was installed: apt
```

### CPU architecture

arm64

### Docker creation

```bash
docker stack deploy -c docker-compose.yml swag
```
```


### Container logs

```bash
swag_swag.0.z43zjc51bgir@nas.my.home    | [migrations] started
swag_swag.0.z43zjc51bgir@nas.my.home    | [migrations] 01-nginx-site-confs-default: skipped
swag_swag.0.z43zjc51bgir@nas.my.home    | [migrations] done
swag_swag.0.z43zjc51bgir@nas.my.home    | [env-init] DNS_CLOUDFLARE_API_TOKEN set from FILE__DNS_CLOUDFLARE_API_TOKEN
swag_swag.0.z43zjc51bgir@nas.my.home    | ───────────────────────────────────────
swag_swag.0.z43zjc51bgir@nas.my.home    | 
swag_swag.0.z43zjc51bgir@nas.my.home    |       ██╗     ███████╗██╗ ██████╗
swag_swag.0.z43zjc51bgir@nas.my.home    |       ██║     ██╔════╝██║██╔═══██╗
swag_swag.0.z43zjc51bgir@nas.my.home    |       ██║     ███████╗██║██║   ██║
swag_swag.0.z43zjc51bgir@nas.my.home    |       ██║     ╚════██║██║██║   ██║
swag_swag.0.z43zjc51bgir@nas.my.home    |       ███████╗███████║██║╚██████╔╝
swag_swag.0.z43zjc51bgir@nas.my.home    |       ╚══════╝╚══════╝╚═╝ ╚═════╝
swag_swag.0.z43zjc51bgir@nas.my.home    | 
swag_swag.0.z43zjc51bgir@nas.my.home    |    Brought to you by linuxserver.io
swag_swag.0.z43zjc51bgir@nas.my.home    | ───────────────────────────────────────
swag_swag.0.z43zjc51bgir@nas.my.home    | 
swag_swag.0.z43zjc51bgir@nas.my.home    | To support the app dev(s) visit:
swag_swag.0.z43zjc51bgir@nas.my.home    | Certbot: https://supporters.eff.org/donate/support-work-on-certbot
swag_swag.0.z43zjc51bgir@nas.my.home    | 
swag_swag.0.z43zjc51bgir@nas.my.home    | To support LSIO projects visit:
swag_swag.0.z43zjc51bgir@nas.my.home    | https://www.linuxserver.io/donate/
swag_swag.0.z43zjc51bgir@nas.my.home    | 
swag_swag.0.z43zjc51bgir@nas.my.home    | ───────────────────────────────────────
swag_swag.0.z43zjc51bgir@nas.my.home    | GID/UID
swag_swag.0.z43zjc51bgir@nas.my.home    | ───────────────────────────────────────
swag_swag.0.z43zjc51bgir@nas.my.home    | 
swag_swag.0.z43zjc51bgir@nas.my.home    | User UID:    1000
swag_swag.0.z43zjc51bgir@nas.my.home    | User GID:    1000
swag_swag.0.z43zjc51bgir@nas.my.home    | ───────────────────────────────────────
swag_swag.0.z43zjc51bgir@nas.my.home    | Linuxserver.io version: 2.11.0-ls327
swag_swag.0.z43zjc51bgir@nas.my.home    | Build-date: 2024-10-05T03:28:09+00:00
swag_swag.0.z43zjc51bgir@nas.my.home    | ───────────────────────────────────────
swag_swag.0.z43zjc51bgir@nas.my.home    |     
swag_swag.0.z43zjc51bgir@nas.my.home    | using keys found in /config/keys
swag_swag.0.z43zjc51bgir@nas.my.home    | Variables set:
swag_swag.0.z43zjc51bgir@nas.my.home    | PUID=1000
swag_swag.0.z43zjc51bgir@nas.my.home    | PGID=1000
swag_swag.0.z43zjc51bgir@nas.my.home    | TZ=Etc/UTC
swag_swag.0.z43zjc51bgir@nas.my.home    | URL=REDACTED
swag_swag.0.z43zjc51bgir@nas.my.home    | SUBDOMAINS=jellyfin1
swag_swag.0.z43zjc51bgir@nas.my.home    | EXTRA_DOMAINS=
swag_swag.0.z43zjc51bgir@nas.my.home    | ONLY_SUBDOMAINS=true
swag_swag.0.z43zjc51bgir@nas.my.home    | VALIDATION=dns
swag_swag.0.z43zjc51bgir@nas.my.home    | CERTPROVIDER=
swag_swag.0.z43zjc51bgir@nas.my.home    | DNSPLUGIN=cloudflare
swag_swag.0.z43zjc51bgir@nas.my.home    | EMAIL=REDACTED
swag_swag.0.z43zjc51bgir@nas.my.home    | STAGING=true
swag_swag.0.z43zjc51bgir@nas.my.home    | 
swag_swag.0.z43zjc51bgir@nas.my.home    | NOTICE: Staging is active
swag_swag.0.z43zjc51bgir@nas.my.home    | Using Let's Encrypt as the cert provider
swag_swag.0.z43zjc51bgir@nas.my.home    | SUBDOMAINS entered, processing
swag_swag.0.z43zjc51bgir@nas.my.home    | Sub-domains processed are: jellyfin1.REDACTED
swag_swag.0.z43zjc51bgir@nas.my.home    | E-mail address entered: REDACTED
swag_swag.0.z43zjc51bgir@nas.my.home    | dns validation via cloudflare plugin is selected
swag_swag.0.z43zjc51bgir@nas.my.home    | Generating new certificate
swag_swag.0.z43zjc51bgir@nas.my.home    | Saving debug log to /var/log/letsencrypt/letsencrypt.log
swag_swag.0.z43zjc51bgir@nas.my.home    | Requesting a certificate for jellyfin1.REDACTED
swag_swag.0.z43zjc51bgir@nas.my.home    | Unsafe permissions on credentials configuration file: /config/dns-conf/cloudflare.ini
swag_swag.0.z43zjc51bgir@nas.my.home    | Error determining zone_id: 6003 Invalid request headers. Please confirm that you have supplied valid Cloudflare API credentials. (Did you copy your entire API token/key? To use Cloudflare tokens, you'll need the python package cloudflare>=2.3.1. This certbot is running cloudflare 2.19.4)
swag_swag.0.z43zjc51bgir@nas.my.home    | Ask for help or search for solutions at https://community.letsencrypt.org. See the logfile /var/log/letsencrypt/letsencrypt.log or re-run Certbot with -v for more details.
swag_swag.0.z43zjc51bgir@nas.my.home    | ERROR: Cert does not exist! Please see the validation error above. Make sure you entered correct credentials into the /config/dns-conf/cloudflare.ini file.
```
```
