### ISSUE TITLE
"ssl3_get_record:wrong version number" after some time

### ISSUE THREAD

**Issue by SyedAmerGilani** [linuxserver/docker-swag#56]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior
Sites can be opened all the time

## Current Behavior
Swag is running fine generally. But from one Linux Host i can not open the pages after a time. When i wait a bit (~ an hour) it works again. In the same time it does not work from this host, i can open the sites from another Host.
Firefox reports "PR_CONNECT_RESET_ERROR".

With curl i get the following:
```
curl -v https://RETRACTED/
*   Trying xx.1.134.102:443...
* Connected to RETRACTED (xx.1.134.102) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/pki/tls/certs/ca-bundle.crt
  CApath: none
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* error:1408F10B:SSL routines:ssl3_get_record:wrong version number
* Closing connection 0
curl: (35) error:1408F10B:SSL routines:ssl3_get_record:wrong version number
```
From another host i can get the site with curl without a Problem. And some time later from this host also again.

## Steps to Reproduce

1. Have swag hosted site open for a while
2. wait
3. reload

## Environment
**OS:** Fedora  33
**CPU architecture:** x86_64
**How docker service was installed:** official docker repo

## Command used to create docker container (run/create/compose/screenshot)

```
swag:
    image: linuxserver/swag
    container_name: swag
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=8675309
      - PGID=8675309
      - TZ=Europe/Berlin
      - URL=RETRACTED
      - SUBDOMAINS=wildcard
      - VALIDATION=dns
      - DNSPLUGIN=cloudflare #optional
      - PROPAGATION= #optional
      - DUCKDNSTOKEN= #optional
      - EMAIL=RETRACTED #optional
      - ONLY_SUBDOMAINS=false #optional
      - EXTRA_DOMAINS=RETRACTED, RETRACTED
      - STAGING=false #optional
    volumes:
      - /opt/appdata/letsencrypt:/config
      - /opt/appdata/nextcloud:/var/www/html
    ports:
      - 443:443
      - 80:80 #optional
    restart: unless-stopped
```
## Docker logs

```
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 01-envfile: executing... 
[cont-init.d] 01-envfile: exited 0.
[cont-init.d] 10-adduser: executing... 
usermod: no changes
-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \ 
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/
Brought to you by linuxserver.io
-------------------------------------
To support the app dev(s) visit:
Certbot: https://supporters.eff.org/donate/support-work-on-certbot
To support LSIO projects visit:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------
User uid:    8675309
User gid:    8675309
-------------------------------------
[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 20-config: executing... 
[cont-init.d] 20-config: exited 0.
[cont-init.d] 30-keygen: executing... 
using keys found in /config/keys
[cont-init.d] 30-keygen: exited 0.
[cont-init.d] 50-config: executing... 
Variables set:
PUID=8675309
PGID=8675309
TZ=Europe/Berlin
URL=RETRACTED
SUBDOMAINS=wildcard
EXTRA_DOMAINS=RETRACTED
ONLY_SUBDOMAINS=false
VALIDATION=dns
DNSPLUGIN=cloudflare
EMAIL=RETRACTED
STAGING=false
SUBDOMAINS entered, processing
Wildcard cert for RETRACTED will be requested
EXTRA_DOMAINS entered, processing
Extra domains processed are:  -d RETRACTED
E-mail address entered: RETRACTED
dns validation via cloudflare plugin is selected
Certificate exists; parameters unchanged; starting nginx
Starting 2019/12/30, GeoIP2 databases require personal license key to download. Please retrieve a free license key from MaxMind,
and add a new env variable "MAXMINDDB_LICENSE_KEY", set to your license key.
[cont-init.d] 50-config: exited 0.
[cont-init.d] 60-renew: executing... 
The cert does not expire within the next day. Letting the cron script handle the renewal attempts overnight (2:08am).
[cont-init.d] 60-renew: exited 0.
[cont-init.d] 70-templates: executing... 
[cont-init.d] 70-templates: exited 0.
[cont-init.d] 99-custom-files: executing... 
[custom-init] no custom files found exiting...
[cont-init.d] 99-custom-files: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
nginx: [alert] detected a LuaJIT version which is not OpenResty's; many optimizations will be disabled and performance will be compromised (see https://github.com/openresty/luajit2 for OpenResty's LuaJIT or, even better, consider using the OpenResty releases from https://openresty.org/en/download.html)
Server ready
```
