### ISSUE TITLE
nginx -t and nginx -s reload not working

### ISSUE THREAD

**Issue by ex0nuss** [linuxserver/docker-swag#57]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior

When using the `nginx -t` command, Nginx should test all configurations for any errors (`-t` = test). This way you can identify errors before restarting the service to avoid downtime. Example with the original Nginx image:
```
docker exec -it backend-nginx nginx -t

nginx: the configuration file /etc/nginx/nginx.conf syntax is ok
nginx: configuration file /etc/nginx/nginx.conf test is successful
```

When using the `nginx -s reload` command, Nginx should reload all the config files without restarting the server (`-s reload` = service reload). This keeps the downtime of the reverse proxy to a minimum. Example with the original Nginx image:
```
docker exec -it backend-nginx nginx -s reload

# If no message gets displayed everything is fine.
```

When restarting the container with `docker-compose up -d --force-recreate` everything runs fine and the nginx config works too. So the nginx config isn't wrong.

Using those two commands is best practice :) You can even set an alias for this to make life easier:
`alias reverseproxyreload='docker exec backend-nginx nginx -t && docker exec backend-nginx nginx -s reload'`

## Current Behavior

```
docker exec -it backend-swag nginx -t

nginx: the configuration file /etc/nginx/nginx.conf syntax is ok
nginx: [emerg] open() "/run/nginx/nginx.pid" failed (2: No such file or directory)
nginx: configuration file /etc/nginx/nginx.conf test failed
```

```
docker exec -it backend-swag nginx -s reload

nginx: [error] open() "/run/nginx/nginx.pid" failed (2: No such file or directory)
```

## Steps to Reproduce

1. Create an swag container.
2. Make changes to the nginx config. E.g.: Create a site
3. run: `docker exec -it YOUR_CONTAINER_NAME nginx -t`
4. run: `docker exec -it YOUR_CONTAINER_NAME nginx -s reload`

## Environment
**OS:** Debian GNU/Linux 9.13 (stretch)
**CPU architecture:** x86_64
**How docker service was installed:** Docker was install using apt-get install ...

## Command used to create docker container (run/create/compose/screenshot)

Using docker compose:
```YAML
version: "3"

services:
  backend-swag:
    image: ghcr.io/linuxserver/swag
    container_name: backend-swag
    restart: unless-stopped
    ports:
      - 9443:443
      - 9080:80
    volumes:
      - ./data-swag:/config
    environment:
      - PUID=996
      - PGID=996
      - TZ=Europe/Berlin
      - URL=XXX.XXX
      - SUBDOMAINS=wildcard
      - VALIDATION=dns
      - DNSPLUGIN=cloudflare
      - EMAIL=XXX@gmail.com
      - MAXMINDDB_LICENSE_KEY=XXX
    cap_add:
      - NET_ADMIN
    labels:
      - com.centurylinklabs.watchtower.enable=true
```

## Docker logs

See "Current Behavior" for outputs.
