### ISSUE TITLE
Unable to get certs from Zerossl - KeyError

### ISSUE THREAD

**Issue by alxsch** [linuxserver/docker-swag#66]
## Expected Behavior
swag should get a certificate from ZeroSSL

## Current Behavior
Getting "Unable to retrieve EAB credentials from ZeroSSL. Check the outgoing connections to api.zerossl.com and dns. Sleeping."

## Steps to Reproduce
1. Ran docker-compose seen below

## Environment
**OS:** Ubuntu Server 20.10
**CPU architecture:** x86_64

**How docker service was installed:**
Followed the directions from the docker docs

## Command used to create docker container (run/create/compose/screenshot)
```
---
version: "2.1"

networks:
  default:
    external:
      name:  ${MAIN_NETWORK}

services:
  swag:
    image: ghcr.io/linuxserver/swag
    container_name: webserver
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
      - URL=${MAIN_DOMAIN}
      - SUBDOMAINS=wildcard
      - VALIDATION=dns
      - CERTPROVIDER=zerossl
      - DNSPLUGIN=cloudflare
      - EMAIL=${ADMIN_EMAIL}
      - ONLY_SUBDOMAINS=true
      - HTTP_PROXY=
      - HTTPS_PROXY=

    volumes:
      - ./config:/config
    ports:
      - 443:443
      - 80:80
    restart: unless-stopped
```

## Docker logs
```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 01-envfile: executing... 
[cont-init.d] 01-envfile: exited 0.
[cont-init.d] 10-adduser: executing... 
usermod: no changes

-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \ 
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/


Brought to you by linuxserver.io
-------------------------------------

To support the app dev(s) visit:
Certbot: https://supporters.eff.org/donate/support-work-on-certbot

To support LSIO projects visit:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------

User uid:    1000
User gid:    1000
-------------------------------------

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 20-config: executing... 
[cont-init.d] 20-config: exited 0.
[cont-init.d] 30-keygen: executing... 
using keys found in /config/keys
[cont-init.d] 30-keygen: exited 0.
[cont-init.d] 50-config: executing... 
Variables set:
PUID=1000
PGID=1000
TZ=America/New_York
URL=example.com
SUBDOMAINS=wildcard
EXTRA_DOMAINS=
ONLY_SUBDOMAINS=true
VALIDATION=dns
CERTPROVIDER=
DNSPLUGIN=cloudflare
EMAIL=example@example.com
STAGING=

Using Let's Encrypt as the cert provider
SUBDOMAINS entered, processing
Wildcard cert for only the subdomains of example.com will be requested
E-mail address entered: example@example.com
dns validation via cloudflare plugin is selected
Different validation parameters entered than what was used before. Revoking and deleting existing certificate, and an updated one will be created
Unable to retrieve EAB credentials from ZeroSSL. Check the outgoing connections to api.zerossl.com and dns. Sleeping.
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.
```

Python error
```
Traceback (most recent call last):
   File "<string>", line 1, in <module>
 KeyError: 'eab_kid'
 Traceback (most recent call last):
   File "<string>", line 1, in <module>
 KeyError: 'eab_hmac_key'
 Unable to retrieve EAB credentials from ZeroSSL. Check the outgoing connections to api.zerossl.com and dns. Sleeping.
```

**Comment by alxsch** [comment]
I am able to ping the api from inside the container.

**Comment by aptalca** [comment]
run this inside the container and see what happens: `curl -i https://api.zerossl.com/acme/eab-credentials-email --data "email=$EMAIL"`

**Comment by alxsch** [comment]
Getting ```HTTP 200 OK```.

**Comment by aptalca** [comment]
Please copy paste the command and the output, you should be getting a lot more than that. Is it giving you an eab_kid and eab_hmac_key? It's ok to partially redact those (make sure you keep the formatting the same)

**Comment by alxsch** [comment]
```
root@8e231370d83a:/# curl -i https://api.zerossl.com/acme/eab-credentials-email --data "email=$EMAIL"
HTTP/1.1 200 OK
server: nginx
content-type: application/json; Charset=UTF-8
transfer-encoding: chunked
access-control-allow-origin: *
access-control-allow-methods: GET, HEAD, POST, PUT, PATCH, DELETE, OPTIONS
x-apilayer-transaction-id: a5a2a7ae-811d-493e-9f7e-1f216e2aea78
cache-control: no-cache, private
date: Tue, 26 Jan 2021 23:17:54 GMT
x-request-time: 0.650

{"success":true,"eab_kid":"G9***","eab_hmac_key":"D***-7***"}
```

**Comment by aptalca** [comment]
That seems fine. Try restarting the container and see if it gets it fine this time. If so, it was temporary connection issue

**Comment by alxsch** [comment]
Docker log

```ZeroSSL is selected as the cert provider, registering cert with ***@***.com
SUBDOMAINS entered, processing
Wildcard cert for only the subdomains of ***.com will be requested
E-mail address entered: schroederalx@gmail.com
dns validation via cloudflare plugin is selected
Different validation parameters entered than what was used before. Revoking and deleting existing certificate, and an updated one will be created
Traceback (most recent call last):
  File "<string>", line 1, in <module>
KeyError: 'eab_kid'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
KeyError: 'eab_hmac_key'
Unable to retrieve EAB credentials from ZeroSSL. Check the outgoing connections to api.zerossl.com and dns. Sleeping.
```

**Comment by alxsch** [comment]
ZeroSSL is selected as the cert provider, registering cert with ***@***.com
SUBDOMAINS entered, processing
Wildcard cert for only the subdomains of ***.com will be requested
E-mail address entered: ***@***.com
dns validation via cloudflare plugin is selected
Different validation parameters entered than what was used before. Revoking and deleting existing certificate, and an updated one will be created
Traceback (most recent call last):
  File "<string>", line 1, in <module>
KeyError: 'eab_kid'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
KeyError: 'eab_hmac_key'
Unable to retrieve EAB credentials from ZeroSSL. Check the outgoing connections to api.zerossl.com and dns. Sleeping.

**Comment by aptalca** [comment]
Honestly, I have no idea. Maybe your container is having connection issues while it's starting up.

The init process runs the same curl command I asked you to test to retrieve the EAB credentials.

**Comment by alxsch** [comment]
Just tried it on my windows machine. Seems to work there seems like it might be some setting in Ubuntu.

**Comment by aptalca** [comment]
it's not creating with le, it's just that the folder is named `letsencrypt` because certbot was originally the official letsencrypt client named `letsencrypt`, so it's just a legacy thing

**Comment by dev-yeet** [comment]
I'm having this issue as well; after looking at the 50-config script, it looks like a space is being inserted into the email address variable 

this is what set -x give sme when i run the script

+ curl -s https://api.zerossl.com/acme/eab-credentials-email --data 'email= testemail@email.com'
+ REV_EAB_CREDS='{"success":false,"error":{"code":2901,"type":"invalid_email"}}'
++ echo '{"success":false,"error":{"code":2901,"type":"invalid_email"}}'
++ python3 -c 'import sys, json; print(json.load(sys.stdin)['\''eab_kid'\''])'

**Comment by aptalca** [comment]
post your compose yaml (or docker run)
I assure you the code does not insert a space as I'm using zerossl on multiple devices

**Comment by dev-yeet** [comment]
alright ignore me. I made a new docker file and copied what I had in clipboard and it seems to work again

```
---
version: "2.1"
services:
  swag:
    image: linuxserver/swag
    container_name: swag
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
      - URL=
      - SUBDOMAINS=
      - CERTPROVIDER=zerossl
      - EMAIL=
    volumes:
      - N:\docker\containers\\linuxserver_swag\config:/config
    ports:
      - 80:80
      - 443:443
    restart: unless-stopped
```
