### ISSUE TITLE
Blank page AdGuard docker-compose

### ISSUE THREAD

**Issue by Erriez** [linuxserver/docker-swag#70]
## Current Behavior
I'm using a `docker-compose.yml` with Swag and including >25 Docker containers on a Raspberry Pi4 aarch64. The only one which does not work is AdGuardhome: It displays a blank page when opening https://adguard.mydomain.nl/install.html.

## Steps to Reproduce
**volumes/swag/config/nginx/proxy-conf/adguard.subdomain.conf**
```yaml
server {
    listen 443 ssl;
    listen [::]:443 ssl;

    server_name adguard.*;

    include /config/nginx/ssl.conf;

    client_max_body_size 0;

     location / {
        include /config/nginx/proxy.conf;
        resolver 127.0.0.11 valid=30s;
        set $upstream_app adguard;
        set $upstream_port 3000;
        set $upstream_proto http;
        proxy_pass $upstream_proto://$upstream_app:$upstream_port;
    }

    location /control {
        include /config/nginx/proxy.conf;
        resolver 127.0.0.11 valid=30s;
        set $upstream_app adguard;
        set $upstream_port 80;
        set $upstream_proto http;
        proxy_pass $upstream_proto://$upstream_app:$upstream_port;
    }
}
```

**docker-compose.yml**
```yaml
version: '3'

services:
  adguard:
    image: adguard/adguardhome
    container_name: adguard
    restart: always
    ports:
      #- 80:80/tcp # Conflict with Swag
      #- 3000:3000/tcp # AdGuard Home service
      #- 67:67/udp # DHCP server not used
      #- 68:68/udp # DHCP server not used
      #- 68:68/tcp # DHCP server not used
      #    https://hub.docker.com/r/adguard/adguardhome
      #    Follow section Running on a system with 'resolved' daemon:
      - 53:53/tcp # DNS
      - 53:53/udp # DNS
      #- 853:853/tcp # DNS-over-TLS server not used
    volumes:
      - ${VOLUME_DIR}/adguard/work:/opt/adguardhome/work
      - ${VOLUME_DIR}/adguard/conf:/opt/adguardhome/conf

  swag:
    image: ghcr.io/linuxserver/swag
    container_name: swag
    restart: always
    ports:
      - 80:80
      - 443:443
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=${UID}
      - PGID=${GID}
      - EMAIL=${SWAG_EMAIL}
      - URL=${ROOT_DOMAIN}
      - SUBDOMAINS=${SWAG_SUBDOMAINS}
      - VALIDATION=${SWAG_VALIDATION}
      - DNSPLUGIN=${SWAG_DNSPLUGIN}
      - ONLY_SUBDOMAINS=${SWAG_ONLY_SUBDOMAINS}
      - TZ=${TZ}
    volumes:
      - ${VOLUME_DIR}/swag/config:/config
```

## Docker logs
```
$ docker-compose up adguard
Starting adguard ... done
Attaching to adguard
adguard          | 2021/02/05 17:10:05 [error] Couldn't read config file /opt/adguardhome/conf/AdGuardHome.yaml: open /opt/adguardhome/conf/AdGuardHome.yaml: no such file or directory
adguard          | 2021/02/05 17:10:05 [info] AdGuard Home, version v0.104.3, channel release, arch linux arm64
adguard          | 2021/02/05 17:10:05 [info] This is the first time AdGuard Home is launched
adguard          | 2021/02/05 17:10:05 [info] Checking if AdGuard Home has necessary permissions
adguard          | 2021/02/05 17:10:05 [info] AdGuard Home can bind to port 53
adguard          | 2021/02/05 17:10:05 [info] Initializing auth module: /opt/adguardhome/work/data/sessions.db
adguard          | 2021/02/05 17:10:05 [info] Auth: initialized.  users:0  sessions:0
adguard          | 2021/02/05 17:10:05 [info] Initialize web module
adguard          | 2021/02/05 17:10:05 [info] This is the first launch of AdGuard Home, redirecting everything to /install.html 
adguard          | 2021/02/05 17:10:05 [info] AdGuard Home is available on the following addresses:
adguard          | 2021/02/05 17:10:05 [info] Go to http://127.0.0.1:3000
adguard          | 2021/02/05 17:10:05 [info] Go to http://172.20.0.17:3000
```

**error.log**
```
Empty.
```

**access.log**
```
<IP> - - [05/Feb/2021:18:28:05 +0100] "GET / HTTP/2.0" 302 36 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:85.0) Gecko/20100101 Firefox/85.0"
<IP> - - [05/Feb/2021:18:28:05 +0100] "GET /install.html HTTP/2.0" 200 477 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:85.0) Gecko/20100101 Firefox/85.0"
```

## Environment
**OS:** `uname -a: Linux raspberry 5.4.0-1028-raspi #31-Ubuntu SMP PREEMPT Wed Jan 20 11:30:45 UTC 2021 aarch64 aarch64 aarch64 GNU/Linux`
**CPU architecture:** `aarch64`
**How docker service was installed:** `sudo apt install docker.io docker-compose`

However, exporting `adguard` container port `3000:3000/tcp` and open the webpage directly on http://raspberry:3000/install.html works.

What could be the problem? Is my configuration wrong?
