### ISSUE TITLE
`docker stack deploy` certbot fails to validate certs

### ISSUE THREAD

**Issue by hughsw** [linuxserver/docker-swag#88]
The certbot in a simple `docker-compose.yml` config fails to validate new certs when used by `docker stack deploy`. 

------------------------------

## Expected Behavior

A simple config that works with `docker-compose up` should also work with `docker stack deploy` (modulo adjusting the version number). 

## Current Behavior

Running `docker stack deploy --compose-file docker-compose.yml swag` fails due to a timeout when certbot is `Waiting for verification...`

Looking at `/var/log/letsencrypt/letsencrypt.log` in the container we find:
> Detail: Fetching http://REDACTED/.well-known/acme-challenge/v6mb6_xO1VbC8GmitS8PILm_2jRR2qs4kDqdmzo-kPI: Timeout after connect (your server may be slow or overloaded)

Note: if I use `docker-compose` to generate the certs, then shut the container down, and then use `docker stack deploy` with the same `docker-compose.yml` file, it works with the certs generated by `docker-compose`.  That implies that the `docker-compose.yml` config file is OK and that the certbot is somehow misconfigured when it's trying to generate the certs.
 However, I didn't wait 90 days to see if the cert can be renewed by the running Docker Stack...

Note: if `user: '1000:1000'` is used in the `docker-compose.yml` with `docker stack deploy`, the container fails very early while trying to run `s6` supervisor at startup.

Also Note: When `docker-compose` is used, all the directories and files created in the `config` directory are owned by uid:1000, gid:1000.  But, when the failing `docker stack deploy` populates the `config` directory, the following subdirectories are owned by root:
* `crontabs`
* `etc`
* `fail2ban`
* `geoip2db`

Also, I have successfully run `linuxserver.io/piwigo` on this same Docker installation using `docker stack deploy` with a config that includes the piwigo image and a mariadb image.  So, I know that `docker stack deploy` can work to bootstrap a new Docker Stack.

## Steps to Reproduce
Create `docker-compose.yml` with the following contents:
```
---
#version: "2.1"  # for `docker-compose up`
version: "3.7"  # for `docker stack deploy`
services:
  swag:
    image: ghcr.io/linuxserver/swag
    cap_add:
    - NET_ADMIN
    environment:
    - PUID=1000
    - PGID=1000
    - TZ=Europe/London
    - URL=<USE_A_DOMAIN_YOU_CONTROL>
    - SUBDOMAINS=media
    - ONLY_SUBDOMAINS=true
    - VALIDATION=http
    volumes:
    - ./config:/config
    ports:
    - 443:443
    - 80:80
```
Be sure you have set up your Docker engine as a Swarm manager via `docker swarm init`, and you may have to use the `--advertise-addr <string>` option, although I didn't have to use it on this installation.

Then run:
```
$ docker stack deploy --compose-file docker-compose.yml swag
```
It will fail with the following error:
```
...

IMPORTANT NOTES:
 - The following errors were reported by the server:
   
   Domain: media.<USE_A_DOMAIN_YOU_CONTROL>
   Type:   connection
   Detail: Fetching
   http://media.<USE_A_DOMAIN_YOU_CONTROL>/.well-known/acme-challenge/v6mb6_xO1VbC8GmitS8PILm_2jRR2qs4kDqdmzo-kPI:
   Timeout after connect (your server may be slow or overloaded)

...
```

## Environment
**OS:** Alpine Linux 3.13 on Linode cloud host
**CPU architecture:**  x86_64
**How docker service was installed:**  `apk add docker` -- standard distribution install

## Command used to create docker container (run/create/compose/screenshot)

See `docker stack deploy ...` above
