### ISSUE TITLE
Container does not work on host with ipv6 disabled

### ISSUE THREAD

**Issue by glensc** [linuxserver/docker-swag#92]
_copied from https://github.com/linuxserver/docker-swag/issues/43#issuecomment-782581808_

```yml
# docker-compose.yml
version: "2.1"

services:
  swag:
    image: ghcr.io/linuxserver/swag
    container_name: swag
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=501
      - PGID=501
      - TZ=Europe/Tallinn
      - URL=dyndns.example.org
      - SUBDOMAINS=
      - VALIDATION=http
      - CERTPROVIDER= #optional
      - DNSPLUGIN=cloudflare #optional
      - PROPAGATION= #optional
      - DUCKDNSTOKEN= #optional
      - EMAIL= #optional
      - ONLY_SUBDOMAINS=false #optional
      - EXTRA_DOMAINS= #optional
      - STAGING=false #optional
      - MAXMINDDB_LICENSE_KEY= #optional
    volumes:
      - ./config:/config
    ports:
      - 443:443
      - 80:80 #optional
    restart: unless-stopped

networks:
  default:
    name: swag

# vim:ts=2:sw=2:et
```

```
glen@acai:~/scm/swag$ docker inspect ghcr.io/linuxserver/swag -f '{{ json .ContainerConfig.Labels }}'  | jq
{
  "build_version": "Linuxserver.io version:- 1.12.0-ls42 Build-date:- 2021-02-18T05:35:06+00:00",
  "maintainer": "aptalca"
}
```

```
glen@acai:~/scm/swag$ rm -rf config

glen@acai:~/scm/swag$ docker-compose up -d
Starting swag ... done

glen@acai:~/scm/swag$ docker-compose logs --tail=20 -t
Attaching to swag                                                                                              
swag    | 2021-02-20T07:44:23.261374104Z [services.d] starting services
swag    | 2021-02-20T07:44:23.287080938Z [services.d] done.
swag    | 2021-02-20T07:44:23.413942329Z nginx: [emerg] socket() [::]:80 failed (97: Address family not support
ed by protocol)
swag    | 2021-02-20T07:44:24.013937160Z Server ready
swag    | 2021-02-20T07:44:24.382779503Z nginx: [emerg] socket() [::]:80 failed (97: Address family not support
ed by protocol)
swag    | 2021-02-20T07:44:25.441645760Z nginx: [emerg] socket() [::]:80 failed (97: Address family not support
ed by protocol)
swag    | 2021-02-20T07:44:26.449157126Z nginx: [emerg] socket() [::]:80 failed (97: Address family not support
ed by protocol)
swag    | 2021-02-20T07:44:27.449683444Z nginx: [emerg] socket() [::]:80 failed (97: Address family not support
ed by protocol)
swag    | 2021-02-20T07:44:28.445631179Z nginx: [emerg] socket() [::]:80 failed (97: Address family not support
ed by protocol)
```

and the service (nginx stays down), connection refused.

```
glen@acai:~/scm/swag$ curl localhost
curl: (56) Recv failure: Connection reset by peer


6 glen@acai:~/scm/swag$ telnet localhost 80
Trying 127.0.0.1...
Connected to localhost.
Escape character is '^]'.
Connection closed by foreign host.
```

It's really connection refused from application point, but docker port forwarding makes error appear as connection reset.

```
glen@acai:~/scm/swag$ docker-compose exec swag netstat -nat|grep LISTEN
tcp        0      0 127.0.0.11:34147        0.0.0.0:*               LISTEN
tcp        0      0 127.0.0.1:9000          0.0.0.0:*               LISTEN
glen@acai:~/scm/swag$
```

ipv6 is disabled via kernel commandline here;

```
glen@acai:~/scm/swag$ cat /proc/cmdline
... ipv6.disable=1
```
